// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];
static TextLayer *s_tl1;
static char s_tl1_buf[4];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(100, 18), 8);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(182, 106), 8);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(100, 194), 8);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(18, 106), 8);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(138, 26), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(168, 58), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(168, 154), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(138, 186), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(54, 186), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(24, 154), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(24, 58), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(54, 26), 4);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
  graphics_fill_circle(ctx, GPoint(102, 112), 12);
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  text_layer_set_text(s_tl0, s_tl0_buf);
  strftime(s_tl1_buf, sizeof(s_tl1_buf), "%S", t);
  text_layer_set_text(s_tl1, s_tl1_buf);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_tl0 = text_layer_create(GRect(0, 68, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  s_tl1 = text_layer_create(GRect(0, 120, 144, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_24));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl1));

  TextLayer *tl_0 = text_layer_create(GRect(0, 155, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Thu 15");
  layer_add_child(root, text_layer_get_layer(tl_0));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  text_layer_destroy(s_tl1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(SECOND_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
