// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static GBitmapSequence *s_seq_spinner;
static GBitmap *s_seqframe_spinner;
static AppTimer *s_seqtimer_spinner;

static void _seq_advance_spinner(void *data);


static void _seq_advance_spinner(void *data) {
  if (!s_seq_spinner || !s_seqframe_spinner) return;
  uint32_t delay_ms = 0;
  bool has_next = gbitmap_sequence_update_bitmap_next_frame(s_seq_spinner, s_seqframe_spinner, &delay_ms);
  if (s_draw_layer) layer_mark_dirty(s_draw_layer);
  if (has_next && delay_ms > 0) {
    s_seqtimer_spinner = app_timer_register(delay_ms, _seq_advance_spinner, NULL);
  } else {
    s_seqtimer_spinner = NULL;
  }
}

static void draw_proc(Layer *layer, GContext *ctx) {
  if (s_seqframe_spinner) {
    graphics_draw_bitmap_in_rect(ctx, s_seqframe_spinner, GRect(76, 76, 48, 48));
  }
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_seq_spinner = gbitmap_sequence_create_with_resource(RESOURCE_ID_SPINNER);
  if (s_seq_spinner) {
    GSize _sz = gbitmap_sequence_get_bitmap_size(s_seq_spinner);
    s_seqframe_spinner = gbitmap_create_blank(_sz, GBitmapFormat8Bit);
    gbitmap_sequence_set_play_count(s_seq_spinner, PLAY_COUNT_INFINITE);
    _seq_advance_spinner(NULL);
  }

  TextLayer *tl_0 = text_layer_create(GRect(0, 12, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Animated APNG");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 170, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xaaaaaa));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "Native gbitmap_sequence");
  layer_add_child(root, text_layer_get_layer(tl_1));

}

static void window_unload(Window *window) {
  if (s_seqtimer_spinner) { app_timer_cancel(s_seqtimer_spinner); s_seqtimer_spinner = NULL; }
  if (s_seqframe_spinner) { gbitmap_destroy(s_seqframe_spinner); s_seqframe_spinner = NULL; }
  if (s_seq_spinner) { gbitmap_sequence_destroy(s_seq_spinner); s_seq_spinner = NULL; }
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
