// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static int s0 = 0;
static bool s1 = true;

static TextLayer *s_ls[6];
static char s_ls_buf[6][32];
static char _msg_buf[512];
static int _data_len = 0;

static void refresh(void) {
}

static void inbox_received(DictionaryIterator *iter, void *ctx) {
  Tuple *t = dict_find(iter, MESSAGE_KEY_items);
  if (t && t->value->cstring) {
    strncpy(_msg_buf, t->value->cstring, sizeof(_msg_buf) - 1);
    // TODO: parse _msg_buf JSON and populate data
    refresh();
  }
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  // List item layers
  s_ls[0] = text_layer_create(GRect(0, 100, 200, 24));
  text_layer_set_background_color(s_ls[0], GColorClear);
  text_layer_set_text_color(s_ls[0], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[0], fonts_get_system_font(FONT_KEY_GOTHIC_24));
  text_layer_set_text_alignment(s_ls[0], GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_ls[0]));
  s_ls[1] = text_layer_create(GRect(0, 100, 144, 24));
  text_layer_set_background_color(s_ls[1], GColorClear);
  text_layer_set_text_color(s_ls[1], GColorWhite);
  text_layer_set_font(s_ls[1], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  layer_add_child(root, text_layer_get_layer(s_ls[1]));
  s_ls[2] = text_layer_create(GRect(0, 124, 144, 24));
  text_layer_set_background_color(s_ls[2], GColorClear);
  text_layer_set_text_color(s_ls[2], GColorWhite);
  text_layer_set_font(s_ls[2], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  layer_add_child(root, text_layer_get_layer(s_ls[2]));
  s_ls[3] = text_layer_create(GRect(0, 124, 144, 24));
  text_layer_set_background_color(s_ls[3], GColorClear);
  text_layer_set_text_color(s_ls[3], GColorWhite);
  text_layer_set_font(s_ls[3], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  layer_add_child(root, text_layer_get_layer(s_ls[3]));
  s_ls[4] = text_layer_create(GRect(0, 148, 144, 24));
  text_layer_set_background_color(s_ls[4], GColorClear);
  text_layer_set_text_color(s_ls[4], GColorWhite);
  text_layer_set_font(s_ls[4], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  layer_add_child(root, text_layer_get_layer(s_ls[4]));
  s_ls[5] = text_layer_create(GRect(0, 148, 144, 24));
  text_layer_set_background_color(s_ls[5], GColorClear);
  text_layer_set_text_color(s_ls[5], GColorWhite);
  text_layer_set_font(s_ls[5], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  layer_add_child(root, text_layer_get_layer(s_ls[5]));

  refresh();
}

static void window_unload(Window *window) {
  for (int i = 0; i < 6; i++) { text_layer_destroy(s_ls[i]); }
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  app_message_register_inbox_received(inbox_received);
  app_message_open(app_message_inbox_size_maximum(), app_message_outbox_size_maximum());
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
