// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;

static TextLayer *s_tl0;
static char s_tl0_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(4, 32, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x000055));
  graphics_fill_rect(ctx, GRect(52, 32, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000aa));
  graphics_fill_rect(ctx, GRect(100, 32, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_rect(ctx, GRect(148, 32, 0, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x005500));
  graphics_fill_rect(ctx, GRect(4, 64, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x005555));
  graphics_fill_rect(ctx, GRect(52, 64, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0055aa));
  graphics_fill_rect(ctx, GRect(100, 64, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0055ff));
  graphics_fill_rect(ctx, GRect(148, 64, 0, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00aa00));
  graphics_fill_rect(ctx, GRect(4, 96, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00aa55));
  graphics_fill_rect(ctx, GRect(52, 96, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00aaaa));
  graphics_fill_rect(ctx, GRect(100, 96, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00aaff));
  graphics_fill_rect(ctx, GRect(148, 96, 0, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_rect(ctx, GRect(4, 128, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff55));
  graphics_fill_rect(ctx, GRect(52, 128, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ffaa));
  graphics_fill_rect(ctx, GRect(100, 128, 44, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ffff));
  graphics_fill_rect(ctx, GRect(148, 128, 0, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x550000));
  graphics_fill_rect(ctx, GRect(4, 160, 44, 8), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x550055));
  graphics_fill_rect(ctx, GRect(52, 160, 44, 8), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x5500aa));
  graphics_fill_rect(ctx, GRect(100, 160, 44, 8), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x5500ff));
  graphics_fill_rect(ctx, GRect(148, 160, 0, 8), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x555500));
  graphics_fill_rect(ctx, GRect(4, 192, 44, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(52, 192, 44, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x5555aa));
  graphics_fill_rect(ctx, GRect(100, 192, 44, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x5555ff));
  graphics_fill_rect(ctx, GRect(148, 192, 0, 0), 0, GCornerNone);
}

static void refresh(void) {
  snprintf(s_tl0_buf, sizeof(s_tl0_buf), "%d", s0);
  text_layer_set_text(s_tl0, s_tl0_buf);
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 1;
  refresh();
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 -= 1;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(4, 4, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "64 Colors");
  layer_add_child(root, text_layer_get_layer(tl_0));

  s_tl0 = text_layer_create(GRect(140, 6, 4, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0x404040));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentRight);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 210, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "UP/DOWN to scroll");
  layer_add_child(root, text_layer_get_layer(tl_1));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
