// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

#define SETTINGS_KEY 1

// MESSAGE_KEY_* constants are auto-generated by the Pebble SDK
// from the "messageKeys" array in package.json.

typedef struct ClaySettings {
  GColor bg;
  GColor fg;
  bool invert;
  char email[64];
  char name[64];
  char fontSize[64];
  char sport[64];
  char units[64];
  bool metrics[3];
} ClaySettings;

static ClaySettings settings;

static void prv_default_settings(void) {
  settings.bg = GColorFromHEX(0x000000);
  settings.fg = GColorFromHEX(0xFFFFFF);
  settings.invert = false;
  strncpy(settings.email, "", sizeof(settings.email) - 1);
  strncpy(settings.name, "Friend", sizeof(settings.name) - 1);
  strncpy(settings.fontSize, "18", sizeof(settings.fontSize) - 1);
  strncpy(settings.sport, "run", sizeof(settings.sport) - 1);
  strncpy(settings.units, "metric", sizeof(settings.units) - 1);
  settings.metrics[0] = true;
  settings.metrics[1] = true;
  settings.metrics[2] = false;
}

static void prv_save_settings(void) {
  persist_write_data(SETTINGS_KEY, &settings, sizeof(settings));
}

static void prv_load_settings(void) {
  prv_default_settings();
  persist_read_data(SETTINGS_KEY, &settings, sizeof(settings));
}

static Window *s_window;


static TextLayer *s_cfg_tl[3];

static void refresh(void) {}

static void prv_update_config(void) {
  window_set_background_color(s_window, settings.bg);
  text_layer_set_text_color(s_cfg_tl[0], settings.fg);
  text_layer_set_text_color(s_cfg_tl[1], settings.fg);
  text_layer_set_text_color(s_cfg_tl[2], settings.fg);
  refresh();
}

static void prv_inbox_received(DictionaryIterator *iter, void *ctx) {
  Tuple *bg_t = dict_find(iter, MESSAGE_KEY_bg);
  if (bg_t) settings.bg = GColorFromHEX(bg_t->value->int32);
  Tuple *fg_t = dict_find(iter, MESSAGE_KEY_fg);
  if (fg_t) settings.fg = GColorFromHEX(fg_t->value->int32);
  Tuple *invert_t = dict_find(iter, MESSAGE_KEY_invert);
  if (invert_t) settings.invert = invert_t->value->int32 == 1;
  Tuple *email_t = dict_find(iter, MESSAGE_KEY_email);
  if (email_t) strncpy(settings.email, email_t->value->cstring, sizeof(settings.email) - 1);
  Tuple *name_t = dict_find(iter, MESSAGE_KEY_name);
  if (name_t) strncpy(settings.name, name_t->value->cstring, sizeof(settings.name) - 1);
  Tuple *fontSize_t = dict_find(iter, MESSAGE_KEY_fontSize);
  if (fontSize_t) strncpy(settings.fontSize, fontSize_t->value->cstring, sizeof(settings.fontSize) - 1);
  Tuple *sport_t = dict_find(iter, MESSAGE_KEY_sport);
  if (sport_t) strncpy(settings.sport, sport_t->value->cstring, sizeof(settings.sport) - 1);
  Tuple *units_t = dict_find(iter, MESSAGE_KEY_units);
  if (units_t) strncpy(settings.units, units_t->value->cstring, sizeof(settings.units) - 1);
  for (int i = 0; i < 3; i++) {
    Tuple *t = dict_find(iter, MESSAGE_KEY_metrics + i);
    if (t) settings.metrics[i] = t->value->int32 == 1;
  }
  prv_save_settings();
  prv_update_config();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_cfg_tl[0] = text_layer_create(GRect(0, 40, 144, 50));
  text_layer_set_background_color(s_cfg_tl[0], GColorClear);
  text_layer_set_text_color(s_cfg_tl[0], GColorWhite);
  text_layer_set_font(s_cfg_tl[0], fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(s_cfg_tl[0], GTextAlignmentCenter);
  text_layer_set_text(s_cfg_tl[0], "Hi Friend");
  layer_add_child(root, text_layer_get_layer(s_cfg_tl[0]));

  s_cfg_tl[1] = text_layer_create(GRect(0, 90, 144, 50));
  text_layer_set_background_color(s_cfg_tl[1], GColorClear);
  text_layer_set_text_color(s_cfg_tl[1], GColorWhite);
  text_layer_set_font(s_cfg_tl[1], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_cfg_tl[1], GTextAlignmentCenter);
  text_layer_set_text(s_cfg_tl[1], "run · metric");
  layer_add_child(root, text_layer_get_layer(s_cfg_tl[1]));

  s_cfg_tl[2] = text_layer_create(GRect(0, 130, 144, 50));
  text_layer_set_background_color(s_cfg_tl[2], GColorClear);
  text_layer_set_text_color(s_cfg_tl[2], GColorWhite);
  text_layer_set_font(s_cfg_tl[2], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_cfg_tl[2], GTextAlignmentCenter);
  text_layer_set_text(s_cfg_tl[2], "pace, hr");
  layer_add_child(root, text_layer_get_layer(s_cfg_tl[2]));

  prv_update_config();
}

static void window_unload(Window *window) {
  for (int i = 0; i < 3; i++) { text_layer_destroy(s_cfg_tl[i]); }
}

static void init(void) {
  prv_load_settings();
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  app_message_register_inbox_received(prv_inbox_received);
  app_message_open(app_message_inbox_size_maximum(), app_message_outbox_size_maximum());
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
