// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

#define SETTINGS_KEY 1

// MESSAGE_KEY_* constants are auto-generated by the Pebble SDK
// from the "messageKeys" array in package.json.

typedef struct ClaySettings {
  GColor bgColor;
  GColor timeColor;
  GColor dateColor;
  bool showSeconds;
  bool showDate;
  char greeting[64];
} ClaySettings;

static ClaySettings settings;

static void prv_default_settings(void) {
  settings.bgColor = GColorFromHEX(0x000000);
  settings.timeColor = GColorFromHEX(0xFFFFFF);
  settings.dateColor = GColorFromHEX(0x55FFFF);
  settings.showSeconds = false;
  settings.showDate = true;
  strncpy(settings.greeting, "Hello!", sizeof(settings.greeting) - 1);
}

static void prv_save_settings(void) {
  persist_write_data(SETTINGS_KEY, &settings, sizeof(settings));
}

static void prv_load_settings(void) {
  prv_default_settings();
  persist_read_data(SETTINGS_KEY, &settings, sizeof(settings));
}

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];
static TextLayer *s_tl1;
static char s_tl1_buf[16];
static TextLayer *s_cfg_tl[1];

static void draw_proc(Layer *layer, GContext *ctx) {
  if (settings.showDate) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x55FFFF));
    graphics_fill_rect(ctx, GRect(40, 120, 104, 1), 0, GCornerNone);
  }
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  if (settings.showSeconds) {
    strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M:%S", t);
  } else {
    strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  }
  text_layer_set_text(s_tl0, s_tl0_buf);
  strftime(s_tl1_buf, sizeof(s_tl1_buf), "%a %b %e", t);
  text_layer_set_text(s_tl1, s_tl1_buf);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}


static void prv_update_config(void) {
  window_set_background_color(s_window, settings.bgColor);
  text_layer_set_text_color(s_cfg_tl[0], settings.dateColor);
  text_layer_set_text(s_cfg_tl[0], settings.greeting);
  text_layer_set_text_color(s_tl0, settings.timeColor);
  text_layer_set_text_color(s_tl1, settings.dateColor);
  // showSeconds toggle
  if (settings.showSeconds) {
    text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_34_MEDIUM_NUMBERS));
  } else {
    text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  }
  layer_set_hidden(text_layer_get_layer(s_tl1), !settings.showDate);
  layer_mark_dirty(s_draw_layer);
  refresh();
}

static void prv_inbox_received(DictionaryIterator *iter, void *ctx) {
  Tuple *bgColor_t = dict_find(iter, MESSAGE_KEY_bgColor);
  if (bgColor_t) settings.bgColor = GColorFromHEX(bgColor_t->value->int32);
  Tuple *timeColor_t = dict_find(iter, MESSAGE_KEY_timeColor);
  if (timeColor_t) settings.timeColor = GColorFromHEX(timeColor_t->value->int32);
  Tuple *dateColor_t = dict_find(iter, MESSAGE_KEY_dateColor);
  if (dateColor_t) settings.dateColor = GColorFromHEX(dateColor_t->value->int32);
  Tuple *showSeconds_t = dict_find(iter, MESSAGE_KEY_showSeconds);
  if (showSeconds_t) settings.showSeconds = showSeconds_t->value->int32 == 1;
  Tuple *showDate_t = dict_find(iter, MESSAGE_KEY_showDate);
  if (showDate_t) settings.showDate = showDate_t->value->int32 == 1;
  Tuple *greeting_t = dict_find(iter, MESSAGE_KEY_greeting);
  if (greeting_t) strncpy(settings.greeting, greeting_t->value->cstring, sizeof(settings.greeting) - 1);
  prv_save_settings();
  prv_update_config();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_cfg_tl[0] = text_layer_create(GRect(0, 30, 144, 50));
  text_layer_set_background_color(s_cfg_tl[0], GColorClear);
  text_layer_set_text_color(s_cfg_tl[0], GColorFromHEX(0x55FFFF));
  text_layer_set_font(s_cfg_tl[0], fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_cfg_tl[0], GTextAlignmentCenter);
  text_layer_set_text(s_cfg_tl[0], "Hello!");
  layer_add_child(root, text_layer_get_layer(s_cfg_tl[0]));

  s_tl0 = text_layer_create(GRect(0, 70, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0xFFFFFF));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  s_tl1 = text_layer_create(GRect(0, 125, 144, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorFromHEX(0x55FFFF));
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_24));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl1));

  refresh();
  prv_update_config();
}

static void window_unload(Window *window) {
  for (int i = 0; i < 1; i++) { text_layer_destroy(s_cfg_tl[i]); }
  text_layer_destroy(s_tl0);
  text_layer_destroy(s_tl1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  prv_load_settings();
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(SECOND_UNIT, tick_handler);
  app_message_register_inbox_received(prv_inbox_received);
  app_message_open(app_message_inbox_size_maximum(), app_message_outbox_size_maximum());
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
