// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static GFont s_font_roboto_24;


static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_font_roboto_24 = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_ROBOTO_24));

  TextLayer *tl_0 = text_layer_create(GRect(0, 20, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorFromHEX(0xaaaaaa));
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "System Gothic 14");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 60, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xffaa55));
  text_layer_set_font(tl_1, s_font_roboto_24);
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "ROBOTO_24");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(0, 100, 144, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, s_font_roboto_24);
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "HELLO WORLD");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(0, 160, 144, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xaaaaaa));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_3, GTextAlignmentCenter);
  text_layer_set_text(tl_3, "System Gothic 18 Bold");
  layer_add_child(root, text_layer_get_layer(tl_3));

}

static void window_unload(Window *window) {
  if (s_font_roboto_24) { fonts_unload_custom_font(s_font_roboto_24); s_font_roboto_24 = NULL; }
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
