// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 24, 134, 64), 8, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 100, 134, 36), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_circle(ctx, GPoint(28, 118), 10);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 140, 134, 28), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_circle(ctx, GPoint(28, 158), 10);
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  text_layer_set_text(s_tl0, s_tl0_buf);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_tl0 = text_layer_create(GRect(10, 32, 134, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_0 = text_layer_create(GRect(10, 72, 134, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Thu 15");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(42, 110, 102, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_1, "Battery: 100%");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(42, 150, 102, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_2, "Connected");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(10, 195, 134, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_3, GTextAlignmentCenter);
  text_layer_set_text(tl_3, "Pebble Dashboard — react-pebble");
  layer_add_child(root, text_layer_get_layer(tl_3));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
