// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;
static Layer *s_br_s2_v0;
static Layer *s_br_s2_v1;

static int s0 = 0;
static int s1 = 0;
static char s2[64] = "";


static void draw_proc(Layer *layer, GContext *ctx) {
  if (strcmp(s2, "") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 32, 144, 28), 0, GCornerNone);
  }
  if (strcmp(s2, "__PROBE__") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 32, 144, 28), 0, GCornerNone);
  }
}

static void refresh(void) {
  layer_set_hidden(s_br_s2_v0, !(strcmp(s2, "") == 0));
  layer_set_hidden(s_br_s2_v1, !(strcmp(s2, "__PROBE__") == 0));
  layer_mark_dirty(s_draw_layer);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 -= 1;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  // Branch: s2 == ""
  s_br_s2_v0 = layer_create(GRect(0, 0, 144, 168));
  layer_add_child(root, s_br_s2_v0);

  TextLayer *tl_0 = text_layer_create(GRect(8, 4, 136, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Notes (5)");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(4, 34, 20, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_1, "○");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(24, 34, 120, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_2, "Buy groceries");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(4, 64, 20, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_3, "○");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(24, 64, 120, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorWhite);
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_4, "Call dentist");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(4, 94, 20, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_5, "○");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(24, 94, 120, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorWhite);
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_6, "Fix bike tire");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(4, 124, 20, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_7, "○");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_7));

  TextLayer *tl_8 = text_layer_create(GRect(24, 124, 120, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorWhite);
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_8, "Read chapter 5");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_8));

  TextLayer *tl_9 = text_layer_create(GRect(4, 154, 20, 50));
  text_layer_set_background_color(tl_9, GColorClear);
  text_layer_set_text_color(tl_9, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_9, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_9, "○");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_9));

  TextLayer *tl_10 = text_layer_create(GRect(24, 154, 120, 50));
  text_layer_set_background_color(tl_10, GColorClear);
  text_layer_set_text_color(tl_10, GColorWhite);
  text_layer_set_font(tl_10, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_10, "Send invoice");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_10));

  TextLayer *tl_11 = text_layer_create(GRect(4, 210, 140, 50));
  text_layer_set_background_color(tl_11, GColorClear);
  text_layer_set_text_color(tl_11, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_11, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_11, "No save file");
  layer_add_child(s_br_s2_v0, text_layer_get_layer(tl_11));

  // Branch: s2 == "__PROBE__"
  s_br_s2_v1 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s2_v1, true);
  layer_add_child(root, s_br_s2_v1);

  TextLayer *tl_12 = text_layer_create(GRect(8, 4, 136, 50));
  text_layer_set_background_color(tl_12, GColorClear);
  text_layer_set_text_color(tl_12, GColorWhite);
  text_layer_set_font(tl_12, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_12, "Notes (5)");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_12));

  TextLayer *tl_13 = text_layer_create(GRect(120, 6, 24, 50));
  text_layer_set_background_color(tl_13, GColorClear);
  text_layer_set_text_color(tl_13, GColorFromHEX(0x00ff00));
  text_layer_set_font(tl_13, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_13, "__PROBE__");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_13));

  TextLayer *tl_14 = text_layer_create(GRect(4, 34, 20, 50));
  text_layer_set_background_color(tl_14, GColorClear);
  text_layer_set_text_color(tl_14, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_14, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_14, "○");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_14));

  TextLayer *tl_15 = text_layer_create(GRect(24, 34, 120, 50));
  text_layer_set_background_color(tl_15, GColorClear);
  text_layer_set_text_color(tl_15, GColorWhite);
  text_layer_set_font(tl_15, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_15, "Buy groceries");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_15));

  TextLayer *tl_16 = text_layer_create(GRect(4, 64, 20, 50));
  text_layer_set_background_color(tl_16, GColorClear);
  text_layer_set_text_color(tl_16, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_16, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_16, "○");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_16));

  TextLayer *tl_17 = text_layer_create(GRect(24, 64, 120, 50));
  text_layer_set_background_color(tl_17, GColorClear);
  text_layer_set_text_color(tl_17, GColorWhite);
  text_layer_set_font(tl_17, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_17, "Call dentist");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_17));

  TextLayer *tl_18 = text_layer_create(GRect(4, 94, 20, 50));
  text_layer_set_background_color(tl_18, GColorClear);
  text_layer_set_text_color(tl_18, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_18, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_18, "○");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_18));

  TextLayer *tl_19 = text_layer_create(GRect(24, 94, 120, 50));
  text_layer_set_background_color(tl_19, GColorClear);
  text_layer_set_text_color(tl_19, GColorWhite);
  text_layer_set_font(tl_19, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_19, "Fix bike tire");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_19));

  TextLayer *tl_20 = text_layer_create(GRect(4, 124, 20, 50));
  text_layer_set_background_color(tl_20, GColorClear);
  text_layer_set_text_color(tl_20, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_20, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_20, "○");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_20));

  TextLayer *tl_21 = text_layer_create(GRect(24, 124, 120, 50));
  text_layer_set_background_color(tl_21, GColorClear);
  text_layer_set_text_color(tl_21, GColorWhite);
  text_layer_set_font(tl_21, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_21, "Read chapter 5");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_21));

  TextLayer *tl_22 = text_layer_create(GRect(4, 154, 20, 50));
  text_layer_set_background_color(tl_22, GColorClear);
  text_layer_set_text_color(tl_22, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_22, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_22, "○");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_22));

  TextLayer *tl_23 = text_layer_create(GRect(24, 154, 120, 50));
  text_layer_set_background_color(tl_23, GColorClear);
  text_layer_set_text_color(tl_23, GColorWhite);
  text_layer_set_font(tl_23, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_23, "Send invoice");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_23));

  TextLayer *tl_24 = text_layer_create(GRect(4, 210, 140, 50));
  text_layer_set_background_color(tl_24, GColorClear);
  text_layer_set_text_color(tl_24, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_24, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_24, "No save file");
  layer_add_child(s_br_s2_v1, text_layer_get_layer(tl_24));

  refresh();
}

static void window_unload(Window *window) {
  layer_destroy(s_br_s2_v0);
  layer_destroy(s_br_s2_v1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
