// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;
static bool s1 = false;
static int s2 = 0;

static TextLayer *s_tl0;
static char s_tl0_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 80, 134, 50), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 138, 134, 30), 6, GCornersAll);
}

static void refresh(void) {
  text_layer_set_text(s_tl0, s1 ? "Acquiring fix..." : "Location acquired");
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(0, 24, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "GPS Location");
  layer_add_child(root, text_layer_get_layer(tl_0));

  s_tl0 = text_layer_create(GRect(0, 56, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0x00ff00));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_1 = text_layer_create(GRect(18, 84, 126, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_1, "Latitude");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(18, 100, 126, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0x00ffff));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD));
  text_layer_set_text(tl_2, "--°");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(18, 142, 126, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_3, "Longitude");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(18, 158, 126, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0x00ffff));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD));
  text_layer_set_text(tl_4, "--°");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_5, GTextAlignmentCenter);
  text_layer_set_text(tl_5, "Press SELECT to refresh");
  layer_add_child(root, text_layer_get_layer(tl_5));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
