// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 70, 85, 50), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(105, 70, 39, 50), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 130, 85, 38), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(105, 130, 39, 38), 0, GCornerNone);
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  text_layer_set_text(s_tl0, s_tl0_buf);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_tl0 = text_layer_create(GRect(0, 10, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_0 = text_layer_create(GRect(10, 72, 85, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Steps");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(10, 88, 85, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0x00ffff));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "5432");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(105, 72, 39, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "Distance");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(105, 88, 39, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0x00ff00));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_3, GTextAlignmentCenter);
  text_layer_set_text(tl_3, "3.8km");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(10, 132, 85, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_4, GTextAlignmentCenter);
  text_layer_set_text(tl_4, "Calories");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(10, 148, 85, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xff8000));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_5, GTextAlignmentCenter);
  text_layer_set_text(tl_5, "210");
  layer_add_child(root, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(105, 132, 39, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_6, GTextAlignmentCenter);
  text_layer_set_text(tl_6, "Heart");
  layer_add_child(root, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(105, 148, 39, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorFromHEX(0xff0000));
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_7, GTextAlignmentCenter);
  text_layer_set_text(tl_7, "72");
  layer_add_child(root, text_layer_get_layer(tl_7));

  TextLayer *tl_8 = text_layer_create(GRect(0, 195, 144, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_8, GTextAlignmentCenter);
  text_layer_set_text(tl_8, "Sleep: 7h 0m");
  layer_add_child(root, text_layer_get_layer(tl_8));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
