// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;
static Layer *s_br_s0_v0;
static Layer *s_br_s0_v1;

static char s0[64] = "list";
static int s1 = 0;

static TextLayer *s_tl1;
static char s_tl1_buf[32];
static TextLayer *s_ls[9];
static char s_ls_buf[9][32];
static const char *_data_key[] = {"PROJ-1", "PROJ-2", "PROJ-3", "PROJ-4", "PROJ-5"};
static const char *_data_summary[] = {"Fix login timeout", "Update dependencies", "Add dark mode", "API rate limiting", "Refactor auth"};
static const char *_data_status[] = {"In Progress", "To Do", "In Review", "In Progress", "To Do"};
static int _data_len = 5;

static void draw_proc(Layer *layer, GContext *ctx) {
  if (strcmp(s0, "list") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorWhite);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(0, 32, 144, 60), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 94, 144, 60), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 156, 144, 12), 0, GCornerNone);
  }
  if (strcmp(s0, "detail") == 0) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
    graphics_fill_circle(ctx, GPoint(18, 118), 8);
  }
}

static void refresh(void) {
  layer_set_hidden(s_br_s0_v0, !(strcmp(s0, "list") == 0));
  layer_set_hidden(s_br_s0_v1, !(strcmp(s0, "detail") == 0));
  layer_mark_dirty(s_draw_layer);
  int _start = s1;
  for (int _i = 0; _i < 3; _i++) {
    int _idx = _start + _i;
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i * 3 + 0], sizeof(s_ls_buf[_i * 3 + 0]), "%s", _data_key[_idx]);
    } else {
      s_ls_buf[_i * 3 + 0][0] = '\0';
    }
    text_layer_set_text(s_ls[_i * 3 + 0], s_ls_buf[_i * 3 + 0]);
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i * 3 + 1], sizeof(s_ls_buf[_i * 3 + 1]), "%s", _data_summary[_idx]);
    } else {
      s_ls_buf[_i * 3 + 1][0] = '\0';
    }
    text_layer_set_text(s_ls[_i * 3 + 1], s_ls_buf[_i * 3 + 1]);
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i * 3 + 2], sizeof(s_ls_buf[_i * 3 + 2]), "%s", _data_status[_idx]);
    } else {
      s_ls_buf[_i * 3 + 2][0] = '\0';
    }
    text_layer_set_text(s_ls[_i * 3 + 2], s_ls_buf[_i * 3 + 2]);
  }
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s1 -= 1;
  if (s1 < 0) s1 = 0;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s1 += 1;
  if (s1 > _data_len - 3) s1 = _data_len - 3;
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s0, "detail", sizeof(s0) - 1);
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  if (strcmp(s0, "list") == 0) {
    window_stack_pop(true);
  } else {
    strncpy(s0, "list", sizeof(s0) - 1);
    refresh();
  }
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  // Branch: s0 == "list"
  s_br_s0_v0 = layer_create(GRect(0, 0, 144, 168));
  layer_add_child(root, s_br_s0_v0);

  TextLayer *tl_0 = text_layer_create(GRect(4, 4, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "JIRA Issues");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_0));

  s_tl1 = text_layer_create(GRect(148, 4, 0, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorFromHEX(0x404040));
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentRight);
  layer_add_child(s_br_s0_v0, text_layer_get_layer(s_tl1));

  // Branch: s0 == "detail"
  s_br_s0_v1 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s0_v1, true);
  layer_add_child(root, s_br_s0_v1);

  TextLayer *tl_1 = text_layer_create(GRect(0, 8, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "PROJ-1");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(10, 50, 134, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text(tl_2, "Fix login timeout");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(30, 106, 114, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorWhite);
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_3, "In Progress");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_4, GTextAlignmentCenter);
  text_layer_set_text(tl_4, "BACK to return");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_4));

  // List item layers
  s_ls[0] = text_layer_create(GRect(8, 4, 184, 24));
  text_layer_set_background_color(s_ls[0], GColorClear);
  text_layer_set_text_color(s_ls[0], GColorWhite);
  text_layer_set_font(s_ls[0], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[0]));
  s_ls[1] = text_layer_create(GRect(8, 26, 184, 24));
  text_layer_set_background_color(s_ls[1], GColorClear);
  text_layer_set_text_color(s_ls[1], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[1], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[1]));
  s_ls[2] = text_layer_create(GRect(8, 42, 184, 24));
  text_layer_set_background_color(s_ls[2], GColorClear);
  text_layer_set_text_color(s_ls[2], GColorFromHEX(0x00ffff));
  text_layer_set_font(s_ls[2], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[2]));
  s_ls[3] = text_layer_create(GRect(8, 4, 184, 24));
  text_layer_set_background_color(s_ls[3], GColorClear);
  text_layer_set_text_color(s_ls[3], GColorWhite);
  text_layer_set_font(s_ls[3], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[3]));
  s_ls[4] = text_layer_create(GRect(8, 26, 184, 24));
  text_layer_set_background_color(s_ls[4], GColorClear);
  text_layer_set_text_color(s_ls[4], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[4], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[4]));
  s_ls[5] = text_layer_create(GRect(8, 42, 184, 24));
  text_layer_set_background_color(s_ls[5], GColorClear);
  text_layer_set_text_color(s_ls[5], GColorFromHEX(0x00ffff));
  text_layer_set_font(s_ls[5], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[5]));
  s_ls[6] = text_layer_create(GRect(8, 4, 184, 24));
  text_layer_set_background_color(s_ls[6], GColorClear);
  text_layer_set_text_color(s_ls[6], GColorWhite);
  text_layer_set_font(s_ls[6], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[6]));
  s_ls[7] = text_layer_create(GRect(8, 26, 184, 24));
  text_layer_set_background_color(s_ls[7], GColorClear);
  text_layer_set_text_color(s_ls[7], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[7], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[7]));
  s_ls[8] = text_layer_create(GRect(8, 42, 184, 24));
  text_layer_set_background_color(s_ls[8], GColorClear);
  text_layer_set_text_color(s_ls[8], GColorFromHEX(0x00ffff));
  text_layer_set_font(s_ls[8], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[8]));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl1);
  for (int i = 0; i < 9; i++) { text_layer_destroy(s_ls[i]); }
  layer_destroy(s_br_s0_v0);
  layer_destroy(s_br_s0_v1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
