// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x000055));
  graphics_fill_rect(ctx, GRect(0, 0, 144, 22), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 28, 134, 36), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_circle(ctx, GPoint(26, 42), 8);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(18, 52, 126, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_rect(ctx, GRect(18, 52, 69, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 68, 134, 36), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_circle(ctx, GPoint(26, 82), 8);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(18, 92, 126, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_rect(ctx, GRect(18, 92, 116, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 108, 134, 36), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
  graphics_fill_circle(ctx, GPoint(26, 122), 8);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(18, 132, 126, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
  graphics_fill_rect(ctx, GRect(18, 132, 126, 8), 3, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(10, 146, 134, 22), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x005500));
  graphics_fill_rect(ctx, GRect(0, 206, 144, 0), 0, GCornerNone);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(0, 2, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "System Stats");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(66, 34, 78, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_1, "CPU");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(174, 34, 0, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_2, GTextAlignmentRight);
  text_layer_set_text(tl_2, "42%");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(66, 74, 78, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorWhite);
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_3, "Memory");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(174, 74, 0, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_4, GTextAlignmentRight);
  text_layer_set_text(tl_4, "71%");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(66, 114, 78, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorWhite);
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_5, "Disk");
  layer_add_child(root, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(174, 114, 0, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_6, GTextAlignmentRight);
  text_layer_set_text(tl_6, "88%");
  layer_add_child(root, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(14, 148, 130, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorBlack);
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_7, "Notes");
  layer_add_child(root, text_layer_get_layer(tl_7));

  TextLayer *tl_8 = text_layer_create(GRect(14, 178, 130, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorWhite);
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_8, "Nested via Card children.");
  layer_add_child(root, text_layer_get_layer(tl_8));

  TextLayer *tl_9 = text_layer_create(GRect(0, 208, 144, 50));
  text_layer_set_background_color(tl_9, GColorClear);
  text_layer_set_text_color(tl_9, GColorWhite);
  text_layer_set_font(tl_9, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_9, GTextAlignmentCenter);
  text_layer_set_text(tl_9, "layered-cards demo");
  layer_add_child(root, text_layer_get_layer(tl_9));

}

static void window_unload(Window *window) {
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
