// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
  graphics_fill_circle(ctx, GPoint(36, 44), 16);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_circle(ctx, GPoint(84, 44), 16);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_circle(ctx, GPoint(132, 44), 16);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xffff00));
  graphics_fill_circle(ctx, GPoint(180, 44), 16);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 68, 134, 30), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 104, 134, 30), 6, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 140, 134, 28), 6, GCornersAll);
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xff00ff));
  graphics_context_set_stroke_width(ctx, 2);
  graphics_draw_line(ctx, GPoint(10, 200), GPoint(60, 220));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0x00ffff));
  graphics_context_set_stroke_width(ctx, 2);
  graphics_draw_line(ctx, GPoint(60, 220), GPoint(110, 200));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xffff00));
  graphics_context_set_stroke_width(ctx, 2);
  graphics_draw_line(ctx, GPoint(110, 200), GPoint(160, 220));
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(0, 4, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Layout Demo");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(18, 74, 126, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_1, "First Card");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(18, 110, 126, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0x00ffff));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_2, "Second Card");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(18, 146, 126, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xff8000));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_3, "Third Card");
  layer_add_child(root, text_layer_get_layer(tl_3));

}

static void window_unload(Window *window) {
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
