// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;
static Layer *s_br_s0_v0;
static Layer *s_br_s0_v1;
static Layer *s_br_s0_v2;

static char s0[64] = "home";


static void draw_proc(Layer *layer, GContext *ctx) {
  if (strcmp(s0, "home") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
  }
  if (strcmp(s0, "settings") == 0) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
  }
  if (strcmp(s0, "about") == 0) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
  }
}

static void refresh(void) {
  layer_set_hidden(s_br_s0_v0, !(strcmp(s0, "home") == 0));
  layer_set_hidden(s_br_s0_v1, !(strcmp(s0, "settings") == 0));
  layer_set_hidden(s_br_s0_v2, !(strcmp(s0, "about") == 0));
  layer_mark_dirty(s_draw_layer);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s0, "settings", sizeof(s0) - 1);
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s0, "about", sizeof(s0) - 1);
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s0, "home", sizeof(s0) - 1);
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  // Branch: s0 == "home"
  s_br_s0_v0 = layer_create(GRect(0, 0, 144, 168));
  layer_add_child(root, s_br_s0_v0);

  TextLayer *tl_0 = text_layer_create(GRect(0, 40, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Home");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 100, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "UP=Settings DOWN=About");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_1));

  // Branch: s0 == "settings"
  s_br_s0_v1 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s0_v1, true);
  layer_add_child(root, s_br_s0_v1);

  TextLayer *tl_2 = text_layer_create(GRect(0, 40, 144, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "Settings");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(10, 100, 134, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorWhite);
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_3, "Brightness: 80%");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_4, GTextAlignmentCenter);
  text_layer_set_text(tl_4, "SELECT for home");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_4));

  // Branch: s0 == "about"
  s_br_s0_v2 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s0_v2, true);
  layer_add_child(root, s_br_s0_v2);

  TextLayer *tl_5 = text_layer_create(GRect(0, 40, 144, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorWhite);
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_5, GTextAlignmentCenter);
  text_layer_set_text(tl_5, "About");
  layer_add_child(s_br_s0_v2, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(10, 100, 134, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorWhite);
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_6, "react-pebble v0.1");
  layer_add_child(s_br_s0_v2, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(10, 130, 134, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_7, "Compiled to piu");
  layer_add_child(s_br_s0_v2, text_layer_get_layer(tl_7));

  TextLayer *tl_8 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_8, GTextAlignmentCenter);
  text_layer_set_text(tl_8, "SELECT for home");
  layer_add_child(s_br_s0_v2, text_layer_get_layer(tl_8));

  refresh();
}

static void window_unload(Window *window) {
  layer_destroy(s_br_s0_v0);
  layer_destroy(s_br_s0_v1);
  layer_destroy(s_br_s0_v2);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
