// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static bool s0 = true;
static bool s1 = true;


static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
  graphics_fill_rect(ctx, GRect(0, 0, 144, 40), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
  graphics_fill_rect(ctx, GRect(0, 188, 144, 0), 0, GCornerNone);
}

static void refresh(void) {
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 = !s0;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s1 = !s1;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(0, 8, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Header");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 100, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "Main Content");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(0, 196, 144, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "Footer");
  layer_add_child(root, text_layer_get_layer(tl_2));

  refresh();
}

static void window_unload(Window *window) {
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
