// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static int s0 = 15;
static bool s1 = false;

static TextLayer *s_tl0;
static char s_tl0_buf[32];
static TextLayer *s_tl1;
static char s_tl1_buf[32];
static TextLayer *s_tl2;
static char s_tl2_buf[32];
static TextLayer *s_tl3;
static char s_tl3_buf[32];

static void refresh(void) {
  snprintf(s_tl1_buf, sizeof(s_tl1_buf), "%d", s0);
  text_layer_set_text(s_tl1, s_tl1_buf);
  text_layer_set_text(s_tl0, s1 ? "Timer set to" : "Set Timer (min)");
  text_layer_set_text(s_tl2, s1 ? "minutes" : "UP/DOWN to adjust");
  text_layer_set_text(s_tl3, s1 ? "BACK to reset" : "SELECT to confirm");
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  if (s0 == 15) {
    window_stack_pop(true);
  } else {
    s0 = 15;
    refresh();
  }
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_tl0 = text_layer_create(GRect(0, 40, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  s_tl1 = text_layer_create(GRect(0, 85, 144, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorWhite);
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl1));

  s_tl2 = text_layer_create(GRect(0, 150, 144, 50));
  text_layer_set_background_color(s_tl2, GColorClear);
  text_layer_set_text_color(s_tl2, GColorFromHEX(0x404040));
  text_layer_set_font(s_tl2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_tl2, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl2));

  s_tl3 = text_layer_create(GRect(0, 180, 144, 50));
  text_layer_set_background_color(s_tl3, GColorClear);
  text_layer_set_text_color(s_tl3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl3, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl3));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  text_layer_destroy(s_tl1);
  text_layer_destroy(s_tl2);
  text_layer_destroy(s_tl3);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
