// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;

static TextLayer *s_tl0;
static char s_tl0_buf[32];
static const GPathInfo s_path0_info = {
  .num_points = 3,
  .points = (GPoint[]) { {0, -50}, {-5, 0}, {5, 0} }
};
static GPath *s_path0;
static const GPathInfo s_path1_info = {
  .num_points = 4,
  .points = (GPoint[]) { {30, 0}, {60, 20}, {30, 40}, {0, 20} }
};
static GPath *s_path1;
static const GPathInfo s_path2_info = {
  .num_points = 7,
  .points = (GPoint[]) { {0, 0}, {20, 15}, {10, 15}, {10, 30}, {-10, 30}, {-10, 15}, {-20, 15} }
};
static GPath *s_path2;

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(100, 100), 3);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
  gpath_draw_filled(ctx, s_path0);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ffff));
  gpath_draw_filled(ctx, s_path1);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xffff00));
  gpath_draw_filled(ctx, s_path2);
}

static void refresh(void) {
  snprintf(s_tl0_buf, sizeof(s_tl0_buf), "%d", s0);
  text_layer_set_text(s_tl0, s_tl0_buf);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 15;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 360;
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  s0 = 0;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_path0 = gpath_create(&s_path0_info);
  gpath_move_to(s_path0, GPoint(100, 100));
  s_path1 = gpath_create(&s_path1_info);
  gpath_move_to(s_path1, GPoint(10, 160));
  s_path2 = gpath_create(&s_path2_info);
  gpath_move_to(s_path2, GPoint(160, 170));

  TextLayer *tl_0 = text_layer_create(GRect(4, 4, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Path / Polygon");
  layer_add_child(root, text_layer_get_layer(tl_0));

  s_tl0 = text_layer_create(GRect(0, 205, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  gpath_destroy(s_path0);
  gpath_destroy(s_path1);
  gpath_destroy(s_path2);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
