// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];
static const GPathInfo s_path0_info = {
  .num_points = 3,
  .points = (GPoint[]) { {0, -34}, {-4, 0}, {4, 0} }
};
static GPath *s_path0;
static const GPathInfo s_path1_info = {
  .num_points = 3,
  .points = (GPoint[]) { {0, -48}, {-3, 0}, {3, 0} }
};
static GPath *s_path1;

static void draw_proc(Layer *layer, GContext *ctx) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);

  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_circle(ctx, GPoint(72, 72), 68);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(72, 9, 3, 10), 0, GCornerNone);
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(99, 26), GPoint(104, 17));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(118, 46), GPoint(127, 41));
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_rect(ctx, GRect(125, 72, 10, 3), 0, GCornerNone);
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(118, 99), GPoint(127, 104));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(99, 118), GPoint(104, 127));
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_rect(ctx, GRect(72, 125, 3, 10), 0, GCornerNone);
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(46, 118), GPoint(41, 127));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(26, 99), GPoint(17, 104));
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_rect(ctx, GRect(9, 72, 10, 3), 0, GCornerNone);
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(26, 45), GPoint(17, 40));
  graphics_context_set_stroke_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_context_set_stroke_width(ctx, 1);
  graphics_draw_line(ctx, GPoint(45, 26), GPoint(40, 17));
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_circle(ctx, GPoint(72, 72), 4);

  // Time-reactive graphics
  {
    int32_t angle = (int32_t)((int64_t)TRIG_MAX_ANGLE * ((t->tm_hour % 12) * 3600 + t->tm_min * 60 + t->tm_sec) / 43200);
    graphics_context_set_fill_color(ctx, GColorWhite);
    gpath_rotate_to(s_path0, angle);
    gpath_draw_filled(ctx, s_path0);
  }
  {
    int32_t angle = TRIG_MAX_ANGLE * (t->tm_min * 60 + t->tm_sec) / 3600;
    graphics_context_set_fill_color(ctx, GColorWhite);
    gpath_rotate_to(s_path1, angle);
    gpath_draw_filled(ctx, s_path1);
  }
  {
    int32_t angle = TRIG_MAX_ANGLE * t->tm_sec / 60;
    GPoint end = {
      .x = 72 + (int16_t)(sin_lookup(angle) * (int32_t)56 / TRIG_MAX_RATIO),
      .y = 72 - (int16_t)(cos_lookup(angle) * (int32_t)56 / TRIG_MAX_RATIO)
    };
    graphics_context_set_stroke_color(ctx, GColorFromHEX(0xff0000));
    graphics_context_set_stroke_width(ctx, 1);
    graphics_draw_line(ctx, GPoint(72, 72), end);
  }
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  text_layer_set_text(s_tl0, s_tl0_buf);
  layer_mark_dirty(s_draw_layer);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_path0 = gpath_create(&s_path0_info);
  gpath_move_to(s_path0, GPoint(72, 72));
  s_path1 = gpath_create(&s_path1_info);
  gpath_move_to(s_path1, GPoint(72, 72));

  s_tl0 = text_layer_create(GRect(0, 140, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  gpath_destroy(s_path0);
  gpath_destroy(s_path1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(SECOND_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
