// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;


static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 28, 144, 30), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 60, 144, 30), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 92, 144, 30), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 124, 144, 30), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 156, 144, 12), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 188, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 220, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 252, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 284, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 316, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 348, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 380, 144, 0), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(62, 164, 20, 3), 0, GCornerNone);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(4, 4, 136, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Docs (paging mode)");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(10, 34, 124, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_1, "1. Introduction");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(10, 66, 124, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_2, "2. Getting Started");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(10, 98, 124, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorWhite);
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_3, "3. Installation");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(10, 130, 124, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorWhite);
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_4, "4. Configuration");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(10, 162, 124, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorWhite);
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_5, "5. Components");
  layer_add_child(root, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(10, 194, 124, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorWhite);
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_6, "6. Hooks");
  layer_add_child(root, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(10, 226, 124, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorWhite);
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_7, "7. Animation");
  layer_add_child(root, text_layer_get_layer(tl_7));

  TextLayer *tl_8 = text_layer_create(GRect(10, 258, 124, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorWhite);
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_8, "8. Sensors");
  layer_add_child(root, text_layer_get_layer(tl_8));

  TextLayer *tl_9 = text_layer_create(GRect(10, 290, 124, 50));
  text_layer_set_background_color(tl_9, GColorClear);
  text_layer_set_text_color(tl_9, GColorWhite);
  text_layer_set_font(tl_9, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_9, "9. Networking");
  layer_add_child(root, text_layer_get_layer(tl_9));

  TextLayer *tl_10 = text_layer_create(GRect(10, 322, 124, 50));
  text_layer_set_background_color(tl_10, GColorClear);
  text_layer_set_text_color(tl_10, GColorWhite);
  text_layer_set_font(tl_10, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_10, "10. Storage");
  layer_add_child(root, text_layer_get_layer(tl_10));

  TextLayer *tl_11 = text_layer_create(GRect(10, 354, 124, 50));
  text_layer_set_background_color(tl_11, GColorClear);
  text_layer_set_text_color(tl_11, GColorWhite);
  text_layer_set_font(tl_11, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_11, "11. Deployment");
  layer_add_child(root, text_layer_get_layer(tl_11));

  TextLayer *tl_12 = text_layer_create(GRect(10, 386, 124, 50));
  text_layer_set_background_color(tl_12, GColorClear);
  text_layer_set_text_color(tl_12, GColorWhite);
  text_layer_set_font(tl_12, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_12, "12. Troubleshooting");
  layer_add_child(root, text_layer_get_layer(tl_12));

}

static void window_unload(Window *window) {
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
