// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;

static TextLayer *s_tl0;
static char s_tl0_buf[32];
static TextLayer *s_ls[6];
static char s_ls_buf[6][32];
static const char *_data_title[] = {"Fix login bug", "Update docs", "Deploy v2", "API rate limit", "Refactor auth"};
static const char *_data_tag[] = {"HIGH", "MED", "LOW", "HIGH", "MED"};
static int _data_len = 5;

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 30), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(0, 34, 144, 58), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 94, 144, 58), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_rect(ctx, GRect(0, 154, 144, 14), 0, GCornerNone);
}

static void refresh(void) {
  snprintf(s_tl0_buf, sizeof(s_tl0_buf), "%d/5", s0 + 1);
  text_layer_set_text(s_tl0, s_tl0_buf);
  int _start = s0;
  for (int _i = 0; _i < 3; _i++) {
    int _idx = _start + _i;
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i * 2 + 0], sizeof(s_ls_buf[_i * 2 + 0]), "%s", _data_title[_idx]);
    } else {
      s_ls_buf[_i * 2 + 0][0] = '\0';
    }
    text_layer_set_text(s_ls[_i * 2 + 0], s_ls_buf[_i * 2 + 0]);
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i * 2 + 1], sizeof(s_ls_buf[_i * 2 + 1]), "%s", _data_tag[_idx]);
    } else {
      s_ls_buf[_i * 2 + 1][0] = '\0';
    }
    text_layer_set_text(s_ls[_i * 2 + 1], s_ls_buf[_i * 2 + 1]);
  }
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 -= 1;
  if (s0 < 0) s0 = 0;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 1;
  if (s0 > _data_len - 3) s0 = _data_len - 3;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(4, 5, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Tasks");
  layer_add_child(root, text_layer_get_layer(tl_0));

  s_tl0 = text_layer_create(GRect(148, 5, 0, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0x404040));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentRight);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  // List item layers
  s_ls[0] = text_layer_create(GRect(8, 6, 140, 24));
  text_layer_set_background_color(s_ls[0], GColorClear);
  text_layer_set_text_color(s_ls[0], GColorWhite);
  text_layer_set_font(s_ls[0], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[0]));
  s_ls[1] = text_layer_create(GRect(8, 30, 140, 24));
  text_layer_set_background_color(s_ls[1], GColorClear);
  text_layer_set_text_color(s_ls[1], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[1], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[1]));
  s_ls[2] = text_layer_create(GRect(8, 6, 140, 24));
  text_layer_set_background_color(s_ls[2], GColorClear);
  text_layer_set_text_color(s_ls[2], GColorWhite);
  text_layer_set_font(s_ls[2], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[2]));
  s_ls[3] = text_layer_create(GRect(8, 30, 140, 24));
  text_layer_set_background_color(s_ls[3], GColorClear);
  text_layer_set_text_color(s_ls[3], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[3], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[3]));
  s_ls[4] = text_layer_create(GRect(8, 6, 140, 24));
  text_layer_set_background_color(s_ls[4], GColorClear);
  text_layer_set_text_color(s_ls[4], GColorWhite);
  text_layer_set_font(s_ls[4], fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(root, text_layer_get_layer(s_ls[4]));
  s_ls[5] = text_layer_create(GRect(8, 30, 140, 24));
  text_layer_set_background_color(s_ls[5], GColorClear);
  text_layer_set_text_color(s_ls[5], GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_ls[5], fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(root, text_layer_get_layer(s_ls[5]));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  for (int i = 0; i < 6; i++) { text_layer_destroy(s_ls[i]); }
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
