// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;
static int s1 = 18;

static TextLayer *s_tl0;
static char s_tl0_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 44, 134, 50), 8, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 102, 134, 50), 8, GCornersAll);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(10, 160, 134, 8), 8, GCornersAll);
}

static void refresh(void) {
  snprintf(s_tl0_buf, sizeof(s_tl0_buf), "%d", s1);
  text_layer_set_text(s_tl0, s_tl0_buf);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s1 += 2;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s1 -= 2;
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 1;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(0, 8, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Settings");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(18, 48, 126, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_1, "Theme (SELECT to cycle)");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(18, 66, 126, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0x00ffff));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text(tl_2, "dark");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(18, 106, 126, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_3, "Font Size (UP/DOWN)");
  layer_add_child(root, text_layer_get_layer(tl_3));

  s_tl0 = text_layer_create(GRect(18, 124, 126, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorFromHEX(0x00ffff));
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_4 = text_layer_create(GRect(18, 164, 126, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_4, "Preview");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(18, 182, 126, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorWhite);
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_5, "Hello Pebble!");
  layer_add_child(root, text_layer_get_layer(tl_5));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
