// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static int s0 = 0;

static TextLayer *s_ls[3];
static char s_ls_buf[3][32];
static const char *_data[] = {"Alpha", "Beta", "Gamma", "Delta", "Epsilon"};
static int _data_len = 5;

static void refresh(void) {
  int _start = s0;
  for (int _i = 0; _i < 3; _i++) {
    int _idx = _start + _i;
    if (_idx < _data_len) {
      snprintf(s_ls_buf[_i], sizeof(s_ls_buf[_i]), "%s", _data[_idx]);
    } else {
      s_ls_buf[_i][0] = '\0';
    }
    text_layer_set_text(s_ls[_i], s_ls_buf[_i]);
  }
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 -= 1;
  if (s0 < 0) s0 = 0;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 1;
  if (s0 > _data_len - 3) s0 = _data_len - 3;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  TextLayer *tl_0 = text_layer_create(GRect(0, 4, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Items");
  layer_add_child(root, text_layer_get_layer(tl_0));

  // List item layers
  s_ls[0] = text_layer_create(GRect(10, 40, 180, 24));
  text_layer_set_background_color(s_ls[0], GColorClear);
  text_layer_set_text_color(s_ls[0], GColorWhite);
  text_layer_set_font(s_ls[0], fonts_get_system_font(FONT_KEY_GOTHIC_24));
  layer_add_child(root, text_layer_get_layer(s_ls[0]));
  s_ls[1] = text_layer_create(GRect(10, 90, 180, 24));
  text_layer_set_background_color(s_ls[1], GColorClear);
  text_layer_set_text_color(s_ls[1], GColorWhite);
  text_layer_set_font(s_ls[1], fonts_get_system_font(FONT_KEY_GOTHIC_24));
  layer_add_child(root, text_layer_get_layer(s_ls[1]));
  s_ls[2] = text_layer_create(GRect(10, 140, 180, 24));
  text_layer_set_background_color(s_ls[2], GColorClear);
  text_layer_set_text_color(s_ls[2], GColorWhite);
  text_layer_set_font(s_ls[2], fonts_get_system_font(FONT_KEY_GOTHIC_24));
  layer_add_child(root, text_layer_get_layer(s_ls[2]));

  refresh();
}

static void window_unload(Window *window) {
  for (int i = 0; i < 3; i++) { text_layer_destroy(s_ls[i]); }
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
