// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static bool s0 = false;
static char s1[64] = "00:00";
static time_t _startTime_s0 = 0;

static TextLayer *s_tl0;
static char s_tl0_buf[32];
static TextLayer *s_tl1;
static char s_tl1_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_circle(ctx, GPoint(100, 84), 60);
  graphics_context_set_fill_color(ctx, GColorBlack);
  graphics_fill_circle(ctx, GPoint(100, 84), 56);
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  if (s0) {
    int _elapsed = (int)(time(NULL) - _startTime_s0);
    snprintf(s_tl0_buf, sizeof(s_tl0_buf), "%02d:%02d", _elapsed / 60, _elapsed % 60);
  } else {
    snprintf(s_tl0_buf, sizeof(s_tl0_buf), "00:00");
  };
  text_layer_set_text(s_tl0, s_tl0_buf);
  text_layer_set_text(s_tl1, s0 ? "RUNNING" : "STOPPED");
  layer_mark_dirty(s_draw_layer);
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  s0 = !s0;
  if (s0) _startTime_s0 = time(NULL);
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s1, "00:00", sizeof(s1) - 1);
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_tl0 = text_layer_create(GRect(0, 55, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  s_tl1 = text_layer_create(GRect(0, 160, 144, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorWhite);
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl1));

  TextLayer *tl_0 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "SELECT start/stop · DOWN reset");
  layer_add_child(root, text_layer_get_layer(tl_0));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  text_layer_destroy(s_tl1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  tick_timer_service_subscribe(SECOND_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
