// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;
static Layer *s_br_s0_v0;
static Layer *s_br_s0_v1;

static char s0[64] = "list";
static int s1 = 0;

static TextLayer *s_tl1;
static char s_tl1_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  if (strcmp(s0, "list") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorWhite);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, (s1 != 0) ? GColorFromHEX(0xblack) : GColorFromHEX(0xdarkGray));
    graphics_fill_rect(ctx, GRect(0, 30, 144, 60), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 92, 144, 60), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 154, 144, 14), 0, GCornerNone);
  }
  if (strcmp(s0, "detail") == 0) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
  }
}

static void refresh(void) {
  layer_mark_dirty(s_draw_layer);
  layer_set_hidden(s_br_s0_v0, !(strcmp(s0, "list") == 0));
  layer_set_hidden(s_br_s0_v1, !(strcmp(s0, "detail") == 0));
  layer_mark_dirty(s_draw_layer);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s1 -= 1;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s1 += 1;
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s0, "detail", sizeof(s0) - 1);
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  if (strcmp(s0, "list") == 0) {
    window_stack_pop(true);
  } else {
    strncpy(s0, "list", sizeof(s0) - 1);
    refresh();
  }
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  // Branch: s0 == "list"
  s_br_s0_v0 = layer_create(GRect(0, 0, 144, 168));
  layer_add_child(root, s_br_s0_v0);

  TextLayer *tl_0 = text_layer_create(GRect(4, 4, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "My Tasks");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_0));

  s_tl1 = text_layer_create(GRect(148, 4, 0, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorFromHEX(0x404040));
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentRight);
  layer_add_child(s_br_s0_v0, text_layer_get_layer(s_tl1));

  TextLayer *tl_1 = text_layer_create(GRect(8, 34, 136, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_1, "Fix login bug");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(8, 52, 136, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_2, "In Progress");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(8, 96, 136, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorWhite);
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_3, "Update docs");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(8, 114, 136, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_4, "To Do");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(8, 158, 136, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorWhite);
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_5, "Deploy v2");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(8, 176, 136, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_6, "Done");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(0, 216, 144, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorFromHEX(0x404040));
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_7, GTextAlignmentCenter);
  text_layer_set_text(tl_7, "UP/DOWN nav, SELECT detail");
  layer_add_child(s_br_s0_v0, text_layer_get_layer(tl_7));

  // Branch: s0 == "detail"
  s_br_s0_v1 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s0_v1, true);
  layer_add_child(root, s_br_s0_v1);

  TextLayer *tl_8 = text_layer_create(GRect(0, 16, 144, 50));
  text_layer_set_background_color(tl_8, GColorClear);
  text_layer_set_text_color(tl_8, GColorWhite);
  text_layer_set_font(tl_8, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_8, GTextAlignmentCenter);
  text_layer_set_text(tl_8, "Task Detail");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_8));

  TextLayer *tl_9 = text_layer_create(GRect(10, 60, 134, 50));
  text_layer_set_background_color(tl_9, GColorClear);
  text_layer_set_text_color(tl_9, GColorWhite);
  text_layer_set_font(tl_9, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text(tl_9, "Task #0");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_9));

  TextLayer *tl_10 = text_layer_create(GRect(10, 90, 134, 50));
  text_layer_set_background_color(tl_10, GColorClear);
  text_layer_set_text_color(tl_10, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_10, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_10, "Status: In Progress");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_10));

  TextLayer *tl_11 = text_layer_create(GRect(10, 120, 134, 50));
  text_layer_set_background_color(tl_11, GColorClear);
  text_layer_set_text_color(tl_11, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_11, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_11, "Priority: High");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_11));

  TextLayer *tl_12 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_12, GColorClear);
  text_layer_set_text_color(tl_12, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_12, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_12, GTextAlignmentCenter);
  text_layer_set_text(tl_12, "BACK to return");
  layer_add_child(s_br_s0_v1, text_layer_get_layer(tl_12));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl1);
  layer_destroy(s_br_s0_v0);
  layer_destroy(s_br_s0_v1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
