// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static bool s0 = false;

static TextLayer *s_tl0;
static char s_tl0_buf[32];

static void refresh(void) {
  text_layer_set_text(s_tl0, s0 ? "ON" : "OFF");
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  s0 = !s0;
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  window_stack_pop(true);
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorFromHEX(0xff0000));

  s_tl0 = text_layer_create(GRect(0, 90, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  TextLayer *tl_0 = text_layer_create(GRect(0, 180, 144, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "SELECT to toggle");
  layer_add_child(root, text_layer_get_layer(tl_0));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
