// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;

static int s0 = 0;
static int s1 = 0;
static int s2 = 0;
static int s3 = 0;


static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  TextLayer *tl_0 = text_layer_create(GRect(4, 8, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(tl_0, GTextAlignmentCenter);
  text_layer_set_text(tl_0, "Identity Tokens");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(4, 40, 140, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xaaffaa));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_1, "Account:");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(4, 58, 140, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_2, "(loading)");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(4, 86, 140, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xaaffaa));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_3, "Watch:");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(4, 104, 140, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorWhite);
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_4, "(loading)");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(4, 132, 140, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xaaffaa));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_5, "Timeline:");
  layer_add_child(root, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(4, 150, 140, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorWhite);
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_6, "(loading)");
  layer_add_child(root, text_layer_get_layer(tl_6));

}

static void window_unload(Window *window) {
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
