// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;
static Layer *s_br_s1_v0;
static Layer *s_br_s1_v1;

static int s0 = 0;
static char s1[64] = "list";

static TextLayer *s_tl10;
static char s_tl10_buf[32];
static TextLayer *s_tl11;
static char s_tl11_buf[32];
static TextLayer *s_tl12;
static char s_tl12_buf[32];
static TextLayer *s_tl13;
static char s_tl13_buf[32];
static TextLayer *s_tl14;
static char s_tl14_buf[32];
static TextLayer *s_tl15;
static char s_tl15_buf[32];
static TextLayer *s_tl16;
static char s_tl16_buf[32];
static TextLayer *s_tl17;
static char s_tl17_buf[32];
static TextLayer *s_tl18;
static char s_tl18_buf[32];
static TextLayer *s_tl19;
static char s_tl19_buf[32];

static void draw_proc(Layer *layer, GContext *ctx) {
  if (strcmp(s1, "list") == 0) {
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 28), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
    graphics_fill_rect(ctx, GRect(4, 34, 140, 58), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0xff0000));
    graphics_fill_circle(ctx, GPoint(22, 59), 12);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(4, 98, 140, 58), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_circle(ctx, GPoint(22, 123), 12);
    graphics_context_set_fill_color(ctx, GColorBlack);
    graphics_fill_rect(ctx, GRect(4, 162, 140, 6), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ff00));
    graphics_fill_circle(ctx, GPoint(22, 187), 12);
  }
  if (strcmp(s1, "detail") == 0) {
    graphics_context_set_fill_color(ctx, GColorFromHEX(0x0000ff));
    graphics_fill_rect(ctx, GRect(0, 0, 144, 168), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorWhite);
    graphics_fill_rect(ctx, GRect(20, 64, 124, 1), 0, GCornerNone);
    graphics_context_set_fill_color(ctx, GColorWhite);
    graphics_fill_rect(ctx, GRect(20, 160, 124, 1), 0, GCornerNone);
  }
}

static void refresh(void) {
  layer_set_hidden(s_br_s1_v0, !(strcmp(s1, "list") == 0));
  layer_set_hidden(s_br_s1_v1, !(strcmp(s1, "detail") == 0));
  layer_mark_dirty(s_draw_layer);
}

static void up_handler(ClickRecognizerRef ref, void *ctx) {
  s0 -= 1;
  refresh();
}

static void down_handler(ClickRecognizerRef ref, void *ctx) {
  s0 += 1;
  refresh();
}

static void select_handler(ClickRecognizerRef ref, void *ctx) {
  strncpy(s1, "detail", sizeof(s1) - 1);
  refresh();
}

static void back_handler(ClickRecognizerRef ref, void *ctx) {
  if (strcmp(s1, "list") == 0) {
    window_stack_pop(true);
  } else {
    strncpy(s1, "list", sizeof(s1) - 1);
    refresh();
  }
}

static void click_config(void *ctx) {
  window_single_click_subscribe(BUTTON_ID_UP, up_handler);
  window_single_click_subscribe(BUTTON_ID_DOWN, down_handler);
  window_single_click_subscribe(BUTTON_ID_SELECT, select_handler);
  window_single_click_subscribe(BUTTON_ID_BACK, back_handler);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  // Branch: s1 == "list"
  s_br_s1_v0 = layer_create(GRect(0, 0, 144, 168));
  layer_add_child(root, s_br_s1_v0);

  TextLayer *tl_0 = text_layer_create(GRect(8, 4, 130, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Central Stn");
  layer_add_child(s_br_s1_v0, text_layer_get_layer(tl_0));

  s_tl10 = text_layer_create(GRect(138, 6, 6, 50));
  text_layer_set_background_color(s_tl10, GColorClear);
  text_layer_set_text_color(s_tl10, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl10, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(s_tl10, GTextAlignmentRight);
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl10));

  s_tl11 = text_layer_create(GRect(40, 40, 100, 50));
  text_layer_set_background_color(s_tl11, GColorClear);
  text_layer_set_text_color(s_tl11, GColorWhite);
  text_layer_set_font(s_tl11, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl11));

  s_tl12 = text_layer_create(GRect(40, 62, 100, 50));
  text_layer_set_background_color(s_tl12, GColorClear);
  text_layer_set_text_color(s_tl12, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl12, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl12));

  s_tl13 = text_layer_create(GRect(142, 44, 2, 50));
  text_layer_set_background_color(s_tl13, GColorClear);
  text_layer_set_text_color(s_tl13, GColorFromHEX(0x00ffff));
  text_layer_set_font(s_tl13, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(s_tl13, GTextAlignmentRight);
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl13));

  s_tl14 = text_layer_create(GRect(40, 104, 100, 50));
  text_layer_set_background_color(s_tl14, GColorClear);
  text_layer_set_text_color(s_tl14, GColorWhite);
  text_layer_set_font(s_tl14, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl14));

  s_tl15 = text_layer_create(GRect(40, 126, 100, 50));
  text_layer_set_background_color(s_tl15, GColorClear);
  text_layer_set_text_color(s_tl15, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl15, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl15));

  s_tl16 = text_layer_create(GRect(142, 108, 2, 50));
  text_layer_set_background_color(s_tl16, GColorClear);
  text_layer_set_text_color(s_tl16, GColorFromHEX(0x00ffff));
  text_layer_set_font(s_tl16, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(s_tl16, GTextAlignmentRight);
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl16));

  s_tl17 = text_layer_create(GRect(40, 168, 100, 50));
  text_layer_set_background_color(s_tl17, GColorClear);
  text_layer_set_text_color(s_tl17, GColorWhite);
  text_layer_set_font(s_tl17, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl17));

  s_tl18 = text_layer_create(GRect(40, 190, 100, 50));
  text_layer_set_background_color(s_tl18, GColorClear);
  text_layer_set_text_color(s_tl18, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl18, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl18));

  s_tl19 = text_layer_create(GRect(142, 172, 2, 50));
  text_layer_set_background_color(s_tl19, GColorClear);
  text_layer_set_text_color(s_tl19, GColorFromHEX(0x00ffff));
  text_layer_set_font(s_tl19, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text_alignment(s_tl19, GTextAlignmentRight);
  layer_add_child(s_br_s1_v0, text_layer_get_layer(s_tl19));

  // Branch: s1 == "detail"
  s_br_s1_v1 = layer_create(GRect(0, 0, 144, 168));
  layer_set_hidden(s_br_s1_v1, true);
  layer_add_child(root, s_br_s1_v1);

  TextLayer *tl_1 = text_layer_create(GRect(0, 10, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "F-Line");
  layer_add_child(s_br_s1_v1, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(0, 44, 144, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "West to Beach");
  layer_add_child(s_br_s1_v1, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(10, 74, 134, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_3, "Next departure:");
  layer_add_child(s_br_s1_v1, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(20, 96, 124, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorWhite);
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text(tl_4, "2 min");
  layer_add_child(s_br_s1_v1, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(0, 200, 144, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_5, GTextAlignmentCenter);
  text_layer_set_text(tl_5, "BACK to return");
  layer_add_child(s_br_s1_v1, text_layer_get_layer(tl_5));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl10);
  text_layer_destroy(s_tl11);
  text_layer_destroy(s_tl12);
  text_layer_destroy(s_tl13);
  text_layer_destroy(s_tl14);
  text_layer_destroy(s_tl15);
  text_layer_destroy(s_tl16);
  text_layer_destroy(s_tl17);
  text_layer_destroy(s_tl18);
  text_layer_destroy(s_tl19);
  layer_destroy(s_br_s1_v0);
  layer_destroy(s_br_s1_v1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_set_click_config_provider(s_window, click_config);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
