// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;


static TextLayer *s_tl0;
static char s_tl0_buf[12];
static TextLayer *s_tl1;
static char s_tl1_buf[16];

static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(20, 80, 124, 1), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xffff00));
  graphics_fill_circle(ctx, GPoint(40, 110), 20);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x404040));
  graphics_fill_rect(ctx, GRect(20, 142, 124, 1), 0, GCornerNone);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xffff00));
  graphics_fill_circle(ctx, GPoint(18, 164), 8);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0xc0c0c0));
  graphics_fill_circle(ctx, GPoint(18, 188), 8);
  graphics_context_set_fill_color(ctx, GColorFromHEX(0x00ffff));
  graphics_fill_circle(ctx, GPoint(18, 212), 8);
}

static void refresh(void) {
  time_t now = time(NULL);
  struct tm *t = localtime(&now);
  strftime(s_tl0_buf, sizeof(s_tl0_buf), "%H:%M", t);
  text_layer_set_text(s_tl0, s_tl0_buf);
  strftime(s_tl1_buf, sizeof(s_tl1_buf), "%a %b %e", t);
  text_layer_set_text(s_tl1, s_tl1_buf);
}

static void tick_handler(struct tm *tick_time, TimeUnits units_changed) {
  refresh();
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  s_tl0 = text_layer_create(GRect(0, 8, 144, 50));
  text_layer_set_background_color(s_tl0, GColorClear);
  text_layer_set_text_color(s_tl0, GColorWhite);
  text_layer_set_font(s_tl0, fonts_get_system_font(FONT_KEY_BITHAM_42_BOLD));
  text_layer_set_text_alignment(s_tl0, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl0));

  s_tl1 = text_layer_create(GRect(0, 55, 144, 50));
  text_layer_set_background_color(s_tl1, GColorClear);
  text_layer_set_text_color(s_tl1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(s_tl1, fonts_get_system_font(FONT_KEY_GOTHIC_18));
  text_layer_set_text_alignment(s_tl1, GTextAlignmentCenter);
  layer_add_child(root, text_layer_get_layer(s_tl1));

  TextLayer *tl_0 = text_layer_create(GRect(70, 90, 74, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorWhite);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_28_BOLD));
  text_layer_set_text(tl_0, "72°F");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(70, 118, 74, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_1, "Sunny");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(32, 152, 40, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorWhite);
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_2, "Thu");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(80, 152, 50, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_3, "75°/58°");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(32, 176, 40, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorWhite);
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_4, "Fri");
  layer_add_child(root, text_layer_get_layer(tl_4));

  TextLayer *tl_5 = text_layer_create(GRect(80, 176, 50, 50));
  text_layer_set_background_color(tl_5, GColorClear);
  text_layer_set_text_color(tl_5, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_5, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_5, "68°/52°");
  layer_add_child(root, text_layer_get_layer(tl_5));

  TextLayer *tl_6 = text_layer_create(GRect(32, 200, 40, 50));
  text_layer_set_background_color(tl_6, GColorClear);
  text_layer_set_text_color(tl_6, GColorWhite);
  text_layer_set_font(tl_6, fonts_get_system_font(FONT_KEY_GOTHIC_14_BOLD));
  text_layer_set_text(tl_6, "Sat");
  layer_add_child(root, text_layer_get_layer(tl_6));

  TextLayer *tl_7 = text_layer_create(GRect(80, 200, 50, 50));
  text_layer_set_background_color(tl_7, GColorClear);
  text_layer_set_text_color(tl_7, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_7, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text(tl_7, "62°/48°");
  layer_add_child(root, text_layer_get_layer(tl_7));

  refresh();
}

static void window_unload(Window *window) {
  text_layer_destroy(s_tl0);
  text_layer_destroy(s_tl1);
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  tick_timer_service_subscribe(MINUTE_UNIT, tick_handler);
  window_stack_push(s_window, true);
}

static void deinit(void) {
  tick_timer_service_unsubscribe();
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
