// Auto-generated by react-pebble (C SDK backend for classic Pebble)
// Target: basalt (144x168)

#include <pebble.h>

static Window *s_window;
static Layer *s_draw_layer;

static int s0 = 0;


static void draw_proc(Layer *layer, GContext *ctx) {
  graphics_context_set_fill_color(ctx, GColorWhite);
  graphics_fill_rect(ctx, GRect(0, 0, 144, 32), 0, GCornerNone);
}

static void window_load(Window *window) {
  Layer *root = window_get_root_layer(window);
  window_set_background_color(window, GColorBlack);

  s_draw_layer = layer_create(GRect(0, 0, 144, 168));
  layer_set_update_proc(s_draw_layer, draw_proc);
  layer_add_child(root, s_draw_layer);

  TextLayer *tl_0 = text_layer_create(GRect(4, 6, 140, 50));
  text_layer_set_background_color(tl_0, GColorClear);
  text_layer_set_text_color(tl_0, GColorBlack);
  text_layer_set_font(tl_0, fonts_get_system_font(FONT_KEY_GOTHIC_18_BOLD));
  text_layer_set_text(tl_0, "Home");
  layer_add_child(root, text_layer_get_layer(tl_0));

  TextLayer *tl_1 = text_layer_create(GRect(0, 80, 144, 50));
  text_layer_set_background_color(tl_1, GColorClear);
  text_layer_set_text_color(tl_1, GColorWhite);
  text_layer_set_font(tl_1, fonts_get_system_font(FONT_KEY_GOTHIC_24_BOLD));
  text_layer_set_text_alignment(tl_1, GTextAlignmentCenter);
  text_layer_set_text(tl_1, "Window Stack");
  layer_add_child(root, text_layer_get_layer(tl_1));

  TextLayer *tl_2 = text_layer_create(GRect(0, 140, 144, 50));
  text_layer_set_background_color(tl_2, GColorClear);
  text_layer_set_text_color(tl_2, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_2, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_2, GTextAlignmentCenter);
  text_layer_set_text(tl_2, "SELECT = Detail");
  layer_add_child(root, text_layer_get_layer(tl_2));

  TextLayer *tl_3 = text_layer_create(GRect(0, 160, 144, 50));
  text_layer_set_background_color(tl_3, GColorClear);
  text_layer_set_text_color(tl_3, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_3, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_3, GTextAlignmentCenter);
  text_layer_set_text(tl_3, "UP = Blue / DOWN = Red");
  layer_add_child(root, text_layer_get_layer(tl_3));

  TextLayer *tl_4 = text_layer_create(GRect(0, 190, 144, 50));
  text_layer_set_background_color(tl_4, GColorClear);
  text_layer_set_text_color(tl_4, GColorFromHEX(0xc0c0c0));
  text_layer_set_font(tl_4, fonts_get_system_font(FONT_KEY_GOTHIC_14));
  text_layer_set_text_alignment(tl_4, GTextAlignmentCenter);
  text_layer_set_text(tl_4, "Depth: 1");
  layer_add_child(root, text_layer_get_layer(tl_4));

}

static void window_unload(Window *window) {
  layer_destroy(s_draw_layer);
}

static void init(void) {
  s_window = window_create();
  window_set_window_handlers(s_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_window, true);
}

static void deinit(void) {
  window_destroy(s_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}
