// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/rich-list.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

const _data = [{"title":"Fix login bug","status":"In Progress"},{"title":"Update docs","status":"To Do"},{"title":"Deploy v2","status":"Done"},{"title":"API rate limit","status":"In Progress"},{"title":"Refactor auth","status":"To Do"}];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this._ls = [];
    const _g0 = c.content("lg0");
    this._ls.push([_g0.content("ls0_0"), _g0.content("ls0_1")]);
    const _g1 = c.content("lg1");
    this._ls.push([_g1.content("ls1_0"), _g1.content("ls1_1")]);
    const _g2 = c.content("lg2");
    this._ls.push([_g2.content("ls2_0"), _g2.content("ls2_1")]);
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 = Math.max(0, this.s0 - 1); this.refresh(); }
    if (name === "down") { this.s0 = Math.min(_data.length - 3, this.s0 + 1); this.refresh(); }
  }
  refresh() {
    const _start = this.s0;
    for (let _i = 0; _i < 3; _i++) {
      const _item = _data[_start + _i];
      const _slot = this._ls[_i];
      if (_slot) {
        _slot[0].string = _item ? _item.title : "";
        _slot[0].visible = !!_item;
        _slot[1].string = _item ? _item.status : "";
        _slot[1].visible = !!_item;
      }
    }
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, top: 0, width: 200, height: 228, skin: sk0 }),
        new Content(null, { left: 0, top: 0, width: 200, height: 28, skin: sk1 }),
        new Label(null, { top: 4, left: 4, width: 192, style: st0, string: "Issues" }),
        new Container(null, { name: "lg0", left: 0, top: 32, contents: [
          new Label(null, { top: 4, left: 8, width: 184, style: st1, name: "ls0_0", string: "Fix login bug" }),
          new Label(null, { top: 26, left: 8, width: 184, style: st2, name: "ls0_1", string: "In Progress" })
        ] }),
        new Container(null, { name: "lg1", left: 0, top: 92, contents: [
          new Label(null, { top: 4, left: 8, width: 184, style: st1, name: "ls1_0", string: "Update docs" }),
          new Label(null, { top: 26, left: 8, width: 184, style: st2, name: "ls1_1", string: "To Do" })
        ] }),
        new Container(null, { name: "lg2", left: 0, top: 152, contents: [
          new Label(null, { top: 4, left: 8, width: 184, style: st1, name: "ls2_0", string: "Deploy v2" }),
          new Label(null, { top: 26, left: 8, width: 184, style: st2, name: "ls2_1", string: "Done" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
