// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/views.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk1 = new Skin({ fill: "#0000ff" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.content("br_s0_v0").first;
    this.s0 = false;
    this.br_s0_v0 = app.content("br_s0_v0");
    this.br_s0_v1 = app.content("br_s0_v1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "select") { this.s0 = !this.s0; this.refresh(); }
  }
  refresh() {
    this.br_s0_v0.visible = (this.s0 === false);
    this.br_s0_v1.visible = (this.s0 === true);
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
    new Container(null, { name: "br_s0_v0", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "List View" }),
          new Label(null, { top: 60, left: 10, width: 180, style: st1, string: "Item 1" }),
          new Label(null, { top: 200, left: 0, width: 200, style: st2, horizontal: "center", string: "SELECT for detail" })
        ] })
    ] }),
    new Container(null, { name: "br_s0_v1", visible: false, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk1 }),
          new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "Detail View" }),
          new Label(null, { top: 60, left: 10, width: 180, style: st1, string: "Name: Widget A" }),
          new Label(null, { top: 90, left: 10, width: 180, style: st1, string: "Status: Active" }),
          new Label(null, { top: 120, left: 10, width: 180, style: st2, string: "Created: 2026-01-15" }),
          new Label(null, { top: 200, left: 0, width: 200, style: st2, horizontal: "center", string: "SELECT to go back" })
        ] })
    ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
