// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/watchface.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "24px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "24px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = "2026-01-14T22:07:03.000Z";
    this.tl0 = c.content("tl0");
    this.tl1 = c.content("tl1");
    this.tl2 = c.content("tl2");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
  }
  onTimeChanged() {
    this.refresh();
  }
  refresh() {
    const d = new Date();
    this.tl0.string = pad(d.getHours()) + ":" + pad(d.getMinutes());
    this.tl1.string = pad(d.getSeconds());
    this.tl2.string = days[d.getDay()] + " " + months[d.getMonth()] + " " + d.getDate();
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, top: 0, width: 200, height: 228, skin: sk0 }),
        new Content(null, { left: 8, top: 24, width: 184, height: 1, skin: sk1 }),
        new Label(null, { top: 50, left: 0, width: 200, style: st0, horizontal: "center", name: "tl0", string: "09:07" }),
        new Label(null, { top: 110, left: 0, width: 200, style: st1, horizontal: "center", name: "tl1", string: "03" }),
        new Content(null, { left: 8, top: 150, width: 184, height: 1, skin: sk1 }),
        new Label(null, { top: 160, left: 0, width: 200, style: st2, horizontal: "center", name: "tl2", string: "Thu Jan 15" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
