/**
 * scripts/targets/pkjs.ts — Shared PKJS sub-output helper.
 *
 * PKJS is a sub-output of each Target (see ADR 0002), not a separate Target.
 * This module is the shared implementation each Adapter calls when its IR
 * demands phone-side code (useMessage, useConfiguration, timeline hooks,
 * identity tokens).
 *
 * Self-contained: owns the PKJS code generator, the config-page data-URI
 * renderer, the needs-PKJS decision rule, and the reserved hook-name table.
 *
 * See: docs/adr/0002-pkjs-as-sub-output.md, docs/adr/0004-adapters-absorb-emit-shells.md
 */

import type { CompilerIR, IRConfigKey } from '../compiler-ir.js';
import {
  ConfigPage,
  ConfigSection,
  ConfigColor,
  ConfigToggle,
  ConfigText,
  configPageToDataUri,
} from '../../src/config/index.js';
import type { TargetName } from './types.js';

// ---------------------------------------------------------------------------
// Needs-PKJS decision
// ---------------------------------------------------------------------------

/** Hook names that require PKJS to be emitted even without messageInfo/configInfo. */
const PKJS_REQUIRING_HOOKS = new Set([
  'useAccountToken',
  'useWatchToken',
  'useTimelineToken',
  'useTimeline',
  'useTimelineSubscriptions',
]);

/** Does this IR require a PKJS sub-output? */
export function needsPKJS(ir: CompilerIR): boolean {
  if (ir.messageInfo) return true;
  if (ir.configInfo) return true;
  return ir.hooksUsed.some((u) => PKJS_REQUIRING_HOOKS.has(u.name));
}

// ---------------------------------------------------------------------------
// PKJS code generator
// ---------------------------------------------------------------------------

export interface PKJSOptions {
  ir: CompilerIR;
  configUrl?: string;
  fetchUrls?: Array<{ key: string; url: string }>;
  appSyncKeys?: string[];
  hooksUsed?: string[];
  target?: TargetName;
}

export function emitPKJS(options: PKJSOptions): string {
  const { ir } = options;
  const hooksUsed = new Set(options.hooksUsed ?? []);
  const wantsAccountToken = hooksUsed.has('useAccountToken');
  const wantsWatchToken = hooksUsed.has('useWatchToken');
  const wantsTimelineToken = hooksUsed.has('useTimelineToken');
  const wantsTimelineSubs = hooksUsed.has('useTimelineSubscriptions');
  const wantsTimeline = hooksUsed.has('useTimeline') || wantsTimelineToken || wantsTimelineSubs;
  const wantsAnyToken = wantsAccountToken || wantsWatchToken || wantsTimelineToken;
  const wantsAppGlance = hooksUsed.has('useAppGlance');
  const wantsInboxHandler = wantsTimelineSubs || wantsTimelineToken || wantsTimeline || wantsAppGlance;

  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * PebbleKit JS companion — auto-generated by react-pebble compiler.');
  lines.push(' * This file runs on the phone and handles communication with the watch.');
  lines.push(' */');
  lines.push('');

  lines.push('Pebble.addEventListener("ready", function() {');
  lines.push('  console.log("PebbleKit JS ready!");');

  if (wantsAnyToken) {
    lines.push('');
    lines.push('  // Forward PebbleKit JS identity tokens to the watch');
    lines.push('  var _rpTokens = {};');
    if (wantsAccountToken) {
      lines.push('  try { _rpTokens._rpTokAcct = Pebble.getAccountToken(); } catch (e) {}');
    }
    if (wantsWatchToken) {
      lines.push('  try { _rpTokens._rpTokWatch = Pebble.getWatchToken(); } catch (e) {}');
    }
    lines.push('  Pebble.sendAppMessage(_rpTokens);');
    if (wantsTimelineToken) {
      lines.push('  // Timeline token is async — forward when it resolves');
      lines.push('  try {');
      lines.push('    Pebble.getTimelineToken(function(tl) {');
      lines.push('      Pebble.sendAppMessage({ _rpTokTL: tl });');
      lines.push('    }, function(err) {');
      lines.push('      Pebble.sendAppMessage({ _rpTokTLErr: String(err) });');
      lines.push('    });');
      lines.push('  } catch (e) {');
      lines.push('    Pebble.sendAppMessage({ _rpTokTLErr: String(e) });');
      lines.push('  }');
    }
  }

  if (wantsTimelineSubs) {
    lines.push('');
    lines.push('  // Forward current timeline subscriptions to the watch');
    lines.push('  try {');
    lines.push('    Pebble.timelineSubscriptions(function(topics) {');
    lines.push('      Pebble.sendAppMessage({ _rpTLSubs: JSON.stringify(topics) });');
    lines.push('    }, function(err) {');
    lines.push('      Pebble.sendAppMessage({ _rpTLSubsErr: String(err) });');
    lines.push('    });');
    lines.push('  } catch (e) {');
    lines.push('    Pebble.sendAppMessage({ _rpTLSubsErr: String(e) });');
    lines.push('  }');
  }

  if (ir.messageInfo) {
    const mi = ir.messageInfo;
    const rocky = options.target === 'rocky';
    if (mi.mockDataSource) {
      lines.push('');
      lines.push('  // Fetch data and send to watch');
      lines.push('  function fetchAndSend() {');
      lines.push(`    var url = ${JSON.stringify(mi.mockDataSource)};`);
      lines.push('    var xhr = new XMLHttpRequest();');
      lines.push('    xhr.onload = function() {');
      lines.push('      try {');
      lines.push('        var data = JSON.parse(this.responseText);');
      lines.push('        var msg = {};');
      if (rocky) {
        lines.push(`        msg["${mi.key}"] = data;`);
        lines.push('        Pebble.postMessage(msg);');
        lines.push('        console.log("Data posted to watch");');
      } else {
        lines.push(`        msg["${mi.key}"] = JSON.stringify(data);`);
        lines.push('        Pebble.sendAppMessage(msg, function() {');
        lines.push('          console.log("Data sent to watch successfully");');
        lines.push('        }, function(e) {');
        lines.push('          console.log("Failed to send data: " + JSON.stringify(e));');
        lines.push('        });');
      }
      lines.push('      } catch (e) {');
      lines.push('        console.log("Parse error: " + e);');
      lines.push('      }');
      lines.push('    };');
      lines.push('    xhr.onerror = function() {');
      lines.push('      console.log("Fetch error for " + url);');
      lines.push('    };');
      lines.push('    xhr.open("GET", url);');
      lines.push('    xhr.send();');
      lines.push('  }');
      lines.push('');
      lines.push('  fetchAndSend();');
    } else {
      lines.push('');
      lines.push(`  // Message key: "${mi.key}"`);
      lines.push('  // Send data to watch using:');
      if (rocky) {
        lines.push(`  //   Pebble.postMessage({ "${mi.key}": yourData });`);
      } else {
        lines.push(`  //   Pebble.sendAppMessage({ "${mi.key}": JSON.stringify(yourData) });`);
      }
    }
  }

  if (options.fetchUrls && options.fetchUrls.length > 0) {
    lines.push('');
    lines.push('  // Proxy fetch requests from watch');
    for (const { key, url } of options.fetchUrls) {
      lines.push(`  (function() {`);
      lines.push(`    var xhr = new XMLHttpRequest();`);
      lines.push(`    xhr.onload = function() {`);
      lines.push(`      var msg = {};`);
      lines.push(`      msg["${key}"] = this.responseText;`);
      lines.push(`      Pebble.sendAppMessage(msg);`);
      lines.push(`    };`);
      lines.push(`    xhr.open("GET", ${JSON.stringify(url)});`);
      lines.push(`    xhr.send();`);
      lines.push(`  })();`);
    }
  }

  lines.push('});');

  if (options.configUrl) {
    // Lookup table for ConfigCheckboxGroup option arrays — used during
    // webviewclosed to convert the submitted string[] (selected option values)
    // to an int[] aligned with the declared options. The C-side reads N
    // consecutive AppMessage slots via pointer arithmetic on MESSAGE_KEY_<key>.
    const checkboxGroups = (ir.configInfo?.keys ?? []).filter(
      (k): k is typeof k & { options: string[] } =>
        k.type === 'checkboxgroup' && Array.isArray(k.options),
    );
    if (checkboxGroups.length > 0) {
      lines.push('');
      lines.push('var __configOptions = {');
      for (const k of checkboxGroups) {
        lines.push(`  "${k.key}": ${JSON.stringify(k.options)},`);
      }
      lines.push('};');
    }

    lines.push('');
    lines.push('// Saved settings (persisted in PebbleKit JS localStorage)');
    lines.push('var savedSettings = null;');
    lines.push('try {');
    lines.push('  var raw = localStorage.getItem("__pebble_config__");');
    lines.push('  if (raw) savedSettings = JSON.parse(raw);');
    lines.push('} catch (e) {}');
    lines.push('');
    lines.push('// Configuration page — pass current settings via URL hash');
    lines.push('Pebble.addEventListener("showConfiguration", function() {');
    lines.push(`  var baseUrl = ${JSON.stringify(options.configUrl)};`);
    lines.push('  var url = baseUrl;');
    lines.push('  if (savedSettings) {');
    lines.push('    url += "#" + encodeURIComponent(JSON.stringify(savedSettings));');
    lines.push('  }');
    lines.push('  Pebble.openURL(url);');
    lines.push('});');
    lines.push('');
    lines.push('Pebble.addEventListener("webviewclosed", function(e) {');
    lines.push('  if (e && e.response) {');
    lines.push('    try {');
    lines.push('      var settings = JSON.parse(decodeURIComponent(e.response));');
    lines.push('      // Save to localStorage so next open shows current values');
    lines.push('      localStorage.setItem("__pebble_config__", JSON.stringify(settings));');
    lines.push('      savedSettings = settings;');
    lines.push('');
    lines.push('      // Convert color strings to integers for C SDK AppMessage');
    lines.push('      var msg = {};');
    lines.push('      for (var key in settings) {');
    lines.push('        var val = settings[key];');
    lines.push('        if (typeof val === "string" && /^[0-9a-fA-F]{6}$/.test(val)) {');
    lines.push('          msg[key] = parseInt(val, 16);  // 0xRRGGBB for GColorFromHEX');
    lines.push('        } else if (typeof val === "boolean") {');
    lines.push('          msg[key] = val ? 1 : 0;');
    lines.push('        } else if (Array.isArray(val) && typeof __configOptions !== "undefined" && __configOptions[key]) {');
    lines.push('          // ConfigCheckboxGroup: convert string[] of selected values to int[]');
    lines.push('          // aligned with the declared options. The Pebble runtime expands the');
    lines.push('          // array into N consecutive AppMessage slots starting at MESSAGE_KEY_<key>.');
    lines.push('          var opts = __configOptions[key];');
    lines.push('          var out = [];');
    lines.push('          for (var i = 0; i < opts.length; i++) {');
    lines.push('            out.push(val.indexOf(opts[i]) >= 0 ? 1 : 0);');
    lines.push('          }');
    lines.push('          msg[key] = out;');
    lines.push('        } else {');
    lines.push('          msg[key] = val;');
    lines.push('        }');
    lines.push('      }');
    lines.push('      Pebble.sendAppMessage(msg, function() {');
    lines.push('        console.log("Settings sent to watch");');
    lines.push('      }, function(err) {');
    lines.push('        console.log("Settings send failed: " + JSON.stringify(err));');
    lines.push('      });');
    lines.push('    } catch (ex) {');
    lines.push('      console.log("Config parse error: " + ex);');
    lines.push('    }');
    lines.push('  }');
    lines.push('});');
  }

  if (options.appSyncKeys && options.appSyncKeys.length > 0) {
    lines.push('');
    lines.push('// AppSync: handle incoming messages from watch');
    lines.push('Pebble.addEventListener("appmessage", function(e) {');
    lines.push('  var payload = e.payload;');
    lines.push('  console.log("Received from watch: " + JSON.stringify(payload));');
    lines.push('');
    lines.push('  // Process each synced key');
    for (const key of options.appSyncKeys) {
      lines.push(`  if (payload["${key}"] !== undefined) {`);
      lines.push(`    // Handle "${key}" update from watch`);
      lines.push(`    console.log("${key} = " + payload["${key}"]);`);
      lines.push('  }');
    }
    lines.push('});');
  }

  if (!options.appSyncKeys?.length && ir.messageInfo) {
    lines.push('');
    lines.push('// Handle messages from watch');
    lines.push('Pebble.addEventListener("appmessage", function(e) {');
    lines.push('  console.log("Received from watch: " + JSON.stringify(e.payload));');
    lines.push('});');
  }

  // Reserved-key inbox handler for timeline / token commands sent from the
  // watch. Runs alongside any other appmessage listeners.
  if (wantsInboxHandler) {
    lines.push('');
    lines.push('// react-pebble timeline / token control channel');
    lines.push('Pebble.addEventListener("appmessage", function(e) {');
    lines.push('  var p = (e && e.payload) || {};');
    if (wantsTimelineToken) {
      lines.push('  if (p._rpTokTLRefresh !== undefined) {');
      lines.push('    try {');
      lines.push('      Pebble.getTimelineToken(function(tl) {');
      lines.push('        Pebble.sendAppMessage({ _rpTokTL: tl });');
      lines.push('      }, function(err) {');
      lines.push('        Pebble.sendAppMessage({ _rpTokTLErr: String(err) });');
      lines.push('      });');
      lines.push('    } catch (ex) { Pebble.sendAppMessage({ _rpTokTLErr: String(ex) }); }');
      lines.push('  }');
    }
    if (wantsTimelineSubs) {
      lines.push('  if (typeof p._rpTLSub === "string") {');
      lines.push('    Pebble.timelineSubscribe(p._rpTLSub, function() {');
      lines.push('      Pebble.timelineSubscriptions(function(topics) {');
      lines.push('        Pebble.sendAppMessage({ _rpTLSubs: JSON.stringify(topics) });');
      lines.push('      });');
      lines.push('    }, function(err) { Pebble.sendAppMessage({ _rpTLSubsErr: String(err) }); });');
      lines.push('  }');
      lines.push('  if (typeof p._rpTLUnsub === "string") {');
      lines.push('    Pebble.timelineUnsubscribe(p._rpTLUnsub, function() {');
      lines.push('      Pebble.timelineSubscriptions(function(topics) {');
      lines.push('        Pebble.sendAppMessage({ _rpTLSubs: JSON.stringify(topics) });');
      lines.push('      });');
      lines.push('    }, function(err) { Pebble.sendAppMessage({ _rpTLSubsErr: String(err) }); });');
      lines.push('  }');
      lines.push('  if (p._rpTLList !== undefined) {');
      lines.push('    Pebble.timelineSubscriptions(function(topics) {');
      lines.push('      Pebble.sendAppMessage({ _rpTLSubs: JSON.stringify(topics) });');
      lines.push('    }, function(err) { Pebble.sendAppMessage({ _rpTLSubsErr: String(err) }); });');
      lines.push('  }');
    }
    if (wantsTimeline) {
      lines.push('  if (typeof p._rpTLPush === "string") {');
      lines.push('    _rpTimelinePush(p._rpTLPush);');
      lines.push('  }');
      lines.push('  if (typeof p._rpTLRemove === "string") {');
      lines.push('    _rpTimelineRemove(p._rpTLRemove);');
      lines.push('  }');
    }
    if (wantsAppGlance) {
      lines.push('  if (typeof p._rpGlanceUpdate === "string") {');
      lines.push('    try {');
      lines.push('      var slices = JSON.parse(p._rpGlanceUpdate);');
      lines.push('      Pebble.appGlanceReload(function(appGlanceSlices) {');
      lines.push('        appGlanceSlices.length = 0;');
      lines.push('        for (var i = 0; i < slices.length; i++) {');
      lines.push('          appGlanceSlices.push(slices[i]);');
      lines.push('        }');
      lines.push('        return slices;');
      lines.push('      }, function() {');
      lines.push('        console.log("AppGlance updated via PKJS");');
      lines.push('      }, function(err) {');
      lines.push('        console.log("AppGlance update failed: " + err);');
      lines.push('      });');
      lines.push('    } catch (e) { console.log("AppGlance parse error: " + e); }');
      lines.push('  }');
    }
    lines.push('});');
  }

  if (wantsTimeline) {
    lines.push('');
    lines.push('// Timeline pin push — forwards pin JSON to Pebble timeline public API.');
    lines.push('function _rpTimelinePush(pinJSON) {');
    lines.push('  var pin;');
    lines.push('  try { pin = JSON.parse(pinJSON); } catch (e) {');
    lines.push('    console.log("Timeline push: invalid JSON: " + e); return;');
    lines.push('  }');
    lines.push('  if (!pin || !pin.id) { console.log("Timeline push: missing id"); return; }');
    lines.push('  Pebble.getTimelineToken(function(tok) {');
    lines.push('    var xhr = new XMLHttpRequest();');
    lines.push('    xhr.open("PUT", "https://timeline-api.rebble.io/v1/user/pins/" + encodeURIComponent(pin.id));');
    lines.push('    xhr.setRequestHeader("Content-Type", "application/json");');
    lines.push('    xhr.setRequestHeader("X-User-Token", tok);');
    lines.push('    xhr.onload = function() {');
    lines.push('      console.log("Timeline push " + pin.id + ": " + xhr.status);');
    lines.push('    };');
    lines.push('    xhr.onerror = function() {');
    lines.push('      console.log("Timeline push " + pin.id + " failed");');
    lines.push('    };');
    lines.push('    xhr.send(JSON.stringify(pin));');
    lines.push('  }, function(err) {');
    lines.push('    console.log("Timeline token fetch failed: " + err);');
    lines.push('  });');
    lines.push('}');
    lines.push('');
    lines.push('function _rpTimelineRemove(id) {');
    lines.push('  Pebble.getTimelineToken(function(tok) {');
    lines.push('    var xhr = new XMLHttpRequest();');
    lines.push('    xhr.open("DELETE", "https://timeline-api.rebble.io/v1/user/pins/" + encodeURIComponent(id));');
    lines.push('    xhr.setRequestHeader("X-User-Token", tok);');
    lines.push('    xhr.onload = function() {');
    lines.push('      console.log("Timeline remove " + id + ": " + xhr.status);');
    lines.push('    };');
    lines.push('    xhr.send();');
    lines.push('  });');
    lines.push('}');
  }

  lines.push('');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Sub-output builder (called by each Target Adapter)
// ---------------------------------------------------------------------------

/**
 * Build PKJS sub-output for a Target.
 *
 * Resolves the config-page data URI (if the app declares `useConfiguration`)
 * and feeds it to the PKJS code generator.
 */
export function buildPKJS(args: {
  ir: CompilerIR;
  target: TargetName;
}): string {
  const { ir, target } = args;
  const configUrl = ir.configInfo?.url ? renderConfigDataUri(ir) : undefined;
  const hooksUsed = [...new Set(ir.hooksUsed.map((u) => u.name))];
  return emitPKJS({ ir, configUrl, hooksUsed, target });
}

function renderConfigDataUri(ir: CompilerIR): string | undefined {
  if (!ir.configInfo) return undefined;

  const sectionTitles = ir.configInfo.sectionTitles.length > 0
    ? ir.configInfo.sectionTitles
    : ['Settings'];

  const colorKeys = ir.configInfo.keys.filter((k) => k.type === 'color');
  const otherKeys = ir.configInfo.keys.filter((k) => k.type !== 'color');

  const makeItem = (k: IRConfigKey) => {
    switch (k.type) {
      case 'color': return ConfigColor(k.key, k.label, String(k.default));
      case 'boolean': return ConfigToggle(k.key, k.label, k.default as boolean);
      case 'string': return ConfigText(k.key, k.label, String(k.default));
      default: return ConfigText(k.key, k.label, String(k.default));
    }
  };

  const sections =
    sectionTitles.length >= 2 && colorKeys.length > 0 && otherKeys.length > 0
      ? [
          ConfigSection(sectionTitles[0]!, colorKeys.map(makeItem)),
          ConfigSection(sectionTitles[1]!, otherKeys.map(makeItem)),
        ]
      : [ConfigSection(sectionTitles[0]!, ir.configInfo.keys.map(makeItem))];

  const spec = ConfigPage(sections, {
    appName: ir.configInfo.appName ?? undefined,
  });
  return configPageToDataUri(spec);
}
