/**
 * scripts/emit-pkjs.ts — PebbleKit JS companion code generator.
 *
 * Generates the phone-side `src/pkjs/index.js` that handles:
 *   - Pebble.addEventListener('ready', ...) initialization
 *   - useFetch proxy: phone fetches URLs and sends data to watch via AppMessage
 *   - useConfiguration: opens config page, receives settings back
 *   - useAppSync: bidirectional message handling
 *   - useMessage: generic message forwarding
 */

import type { CompilerIR } from './compiler-ir.js';

export interface PKJSOptions {
  /** The IR from the analyze phase */
  ir: CompilerIR;
  /** Configuration page URL (from useConfiguration) */
  configUrl?: string;
  /** Fetch URLs to proxy (from useFetch mockData patterns) */
  fetchUrls?: Array<{ key: string; url: string }>;
  /** AppSync keys (from useAppSync) */
  appSyncKeys?: string[];
}

/**
 * Generate PebbleKit JS companion code from the compiler IR.
 *
 * This generates a standard phone-side index.js that:
 * 1. Listens for the 'ready' event
 * 2. Handles fetch proxying for useFetch hooks
 * 3. Opens configuration pages and relays settings
 * 4. Handles bidirectional AppSync communication
 */
export function emitPKJS(options: PKJSOptions): string {
  const { ir } = options;
  const lines: string[] = [];

  lines.push('/**');
  lines.push(' * PebbleKit JS companion — auto-generated by react-pebble compiler.');
  lines.push(' * This file runs on the phone and handles communication with the watch.');
  lines.push(' */');
  lines.push('');

  // Ready handler
  lines.push('Pebble.addEventListener("ready", function() {');
  lines.push('  console.log("PebbleKit JS ready!");');

  // If we have message info with mock data, generate the fetch proxy
  if (ir.messageInfo) {
    const mi = ir.messageInfo;
    if (mi.mockDataSource) {
      lines.push('');
      lines.push('  // Fetch data and send to watch');
      lines.push('  function fetchAndSend() {');
      lines.push(`    var url = ${JSON.stringify(mi.mockDataSource)};`);
      lines.push('    var xhr = new XMLHttpRequest();');
      lines.push('    xhr.onload = function() {');
      lines.push('      try {');
      lines.push('        var data = JSON.parse(this.responseText);');
      lines.push('        var msg = {};');
      lines.push(`        msg["${mi.key}"] = JSON.stringify(data);`);
      lines.push('        Pebble.sendAppMessage(msg, function() {');
      lines.push('          console.log("Data sent to watch successfully");');
      lines.push('        }, function(e) {');
      lines.push('          console.log("Failed to send data: " + JSON.stringify(e));');
      lines.push('        });');
      lines.push('      } catch (e) {');
      lines.push('        console.log("Parse error: " + e);');
      lines.push('      }');
      lines.push('    };');
      lines.push('    xhr.onerror = function() {');
      lines.push('      console.log("Fetch error for " + url);');
      lines.push('    };');
      lines.push('    xhr.open("GET", url);');
      lines.push('    xhr.send();');
      lines.push('  }');
      lines.push('');
      lines.push('  fetchAndSend();');
    } else {
      // No mock data URL — just set up message listener
      lines.push('');
      lines.push(`  // Message key: "${mi.key}"`);
      lines.push('  // Send data to watch using:');
      lines.push(`  //   Pebble.sendAppMessage({ "${mi.key}": JSON.stringify(yourData) });`);
    }
  }

  // Additional fetch URL proxying
  if (options.fetchUrls && options.fetchUrls.length > 0) {
    lines.push('');
    lines.push('  // Proxy fetch requests from watch');
    for (const { key, url } of options.fetchUrls) {
      lines.push(`  (function() {`);
      lines.push(`    var xhr = new XMLHttpRequest();`);
      lines.push(`    xhr.onload = function() {`);
      lines.push(`      var msg = {};`);
      lines.push(`      msg["${key}"] = this.responseText;`);
      lines.push(`      Pebble.sendAppMessage(msg);`);
      lines.push(`    };`);
      lines.push(`    xhr.open("GET", ${JSON.stringify(url)});`);
      lines.push(`    xhr.send();`);
      lines.push(`  })();`);
    }
  }

  lines.push('});');

  // Configuration page support
  if (options.configUrl) {
    lines.push('');
    lines.push('// Saved settings (persisted in PebbleKit JS localStorage)');
    lines.push('var savedSettings = null;');
    lines.push('try {');
    lines.push('  var raw = localStorage.getItem("__pebble_config__");');
    lines.push('  if (raw) savedSettings = JSON.parse(raw);');
    lines.push('} catch (e) {}');
    lines.push('');
    lines.push('// Configuration page — pass current settings via URL hash');
    lines.push('Pebble.addEventListener("showConfiguration", function() {');
    lines.push(`  var baseUrl = ${JSON.stringify(options.configUrl)};`);
    lines.push('  var url = baseUrl;');
    lines.push('  if (savedSettings) {');
    lines.push('    url += "#" + encodeURIComponent(JSON.stringify(savedSettings));');
    lines.push('  }');
    lines.push('  Pebble.openURL(url);');
    lines.push('});');
    lines.push('');
    lines.push('Pebble.addEventListener("webviewclosed", function(e) {');
    lines.push('  if (e && e.response) {');
    lines.push('    try {');
    lines.push('      var settings = JSON.parse(decodeURIComponent(e.response));');
    lines.push('      // Save to localStorage so next open shows current values');
    lines.push('      localStorage.setItem("__pebble_config__", JSON.stringify(settings));');
    lines.push('      savedSettings = settings;');
    lines.push('');
    lines.push('      // Convert color strings to integers for C SDK AppMessage');
    lines.push('      var msg = {};');
    lines.push('      for (var key in settings) {');
    lines.push('        var val = settings[key];');
    lines.push('        if (typeof val === "string" && /^[0-9a-fA-F]{6}$/.test(val)) {');
    lines.push('          msg[key] = parseInt(val, 16);  // 0xRRGGBB for GColorFromHEX');
    lines.push('        } else if (typeof val === "boolean") {');
    lines.push('          msg[key] = val ? 1 : 0;');
    lines.push('        } else {');
    lines.push('          msg[key] = val;');
    lines.push('        }');
    lines.push('      }');
    lines.push('      Pebble.sendAppMessage(msg, function() {');
    lines.push('        console.log("Settings sent to watch");');
    lines.push('      }, function(err) {');
    lines.push('        console.log("Settings send failed: " + JSON.stringify(err));');
    lines.push('      });');
    lines.push('    } catch (ex) {');
    lines.push('      console.log("Config parse error: " + ex);');
    lines.push('    }');
    lines.push('  }');
    lines.push('});');
  }

  // AppSync bidirectional handling
  if (options.appSyncKeys && options.appSyncKeys.length > 0) {
    lines.push('');
    lines.push('// AppSync: handle incoming messages from watch');
    lines.push('Pebble.addEventListener("appmessage", function(e) {');
    lines.push('  var payload = e.payload;');
    lines.push('  console.log("Received from watch: " + JSON.stringify(payload));');
    lines.push('');
    lines.push('  // Process each synced key');
    for (const key of options.appSyncKeys) {
      lines.push(`  if (payload["${key}"] !== undefined) {`);
      lines.push(`    // Handle "${key}" update from watch`);
      lines.push(`    console.log("${key} = " + payload["${key}"]);`);
      lines.push('  }');
    }
    lines.push('});');
  }

  // Generic appmessage handler (if no AppSync but has message info)
  if (!options.appSyncKeys?.length && ir.messageInfo) {
    lines.push('');
    lines.push('// Handle messages from watch');
    lines.push('Pebble.addEventListener("appmessage", function(e) {');
    lines.push('  console.log("Received from watch: " + JSON.stringify(e.payload));');
    lines.push('});');
  }

  lines.push('');
  return lines.join('\n');
}
