// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;
var s1 = "";

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Actions', 4, 4);
  ctx.fillStyle = (s0 !== 0) ? 'black' : 'white';
  ctx.fillRect(0, 30, 200, 42);
  ctx.fillStyle = '#000000';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Reply', 12, 40);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 74, 200, 42);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Dismiss', 12, 84);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 118, 200, 42);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Mute', 12, 128);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 162, 200, 42);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Open on Phone', 12, 172);
});
