// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.beginPath();
  ctx.arc(100, 18, 8, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ffffff';
  ctx.beginPath();
  ctx.arc(182, 106, 8, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ffffff';
  ctx.beginPath();
  ctx.arc(100, 194, 8, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ffffff';
  ctx.beginPath();
  ctx.arc(18, 106, 8, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(138, 26, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(168, 58, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(168, 154, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(138, 186, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(54, 186, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(24, 154, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(24, 58, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#c0c0c0';
  ctx.beginPath();
  ctx.arc(54, 26, 4, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ff0000';
  ctx.beginPath();
  ctx.arc(102, 112, 12, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 100, 68);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '24px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getSeconds()), 100, 120);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Thu 15', 100, 155);
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
