// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


var _kf_e1_top = [30,30,31,32,34,37,40,43,47,52,57,63,69,76,84,91,100,109,118,129,139,150,159,153,148,144,140,136,134,131,130,128,128,128,128,129,130,132,135,138,142,146,151,156,159,156,154,153,152,152,152,153,154,156,158,159,158,158,158,159];
var _kf_e2_width = [16,16,16,16,16,16,16,16,16,16,16,16,18,18,18,18,18,20,20,20,22,22,22,24,24,26,28,28,30,32,34,34,36,38,38,40,42,42,44,44,44,46,46,46,48,48,48,48,48,50,50,50,50,50,50,50,50,50,50,50];
var _kf_e2_height = [16,16,16,16,16,16,16,16,16,16,16,16,18,18,18,18,18,20,20,20,22,22,22,24,24,26,28,28,30,32,34,34,36,38,38,40,42,42,44,44,44,46,46,46,48,48,48,48,48,50,50,50,50,50,50,50,50,50,50,50];
var _kf_e2_radius = [8,8,8,8,8,8,8,8,8,8,8,8,9,9,9,9,9,10,10,10,11,11,11,12,12,13,14,14,15,16,17,17,18,19,19,20,21,21,22,22,22,23,23,23,24,24,24,24,24,25,25,25,25,25,25,25,25,25,25,25];
var _kf_e4_width = [0,0,0,0,0,0,1,1,2,2,3,4,6,7,9,11,14,16,19,23,27,31,35,41,46,52,59,66,73,81,90,99,107,114,121,128,134,139,145,149,153,157,161,164,166,169,171,173,174,176,177,178,178,179,179,180,180,180,180,180];

rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Animation Demo', 100, 4);
  ctx.fillStyle = '#ff0000';
  ctx.rockyFillRadial(32, 44, 0, 12, 0, 2 * Math.PI);
  ctx.fillStyle = '#00ffff';
  ctx.rockyFillRadial(138, 98, 0, 8, 0, 2 * Math.PI);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 190, 180, 10);
  ctx.fillStyle = '#00ff00';
  ctx.fillRect(10, 190, 0, 10);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getMinutes()) + ":" + pad(d.getSeconds()), 100, 205);

  // Note: animations use pre-computed keyframe tables
  // Rocky.js redraws fully, so animated positions are computed inline above
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
