// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Animated APNG', 100, 12);
  // image: assets/images/spinner.apng
  if (typeof _images !== 'undefined' && _images["assets/images/spinner.apng"]) {
    ctx.drawImage(_images["assets/images/spinner.apng"], 76, 76);
  } else {
    ctx.fillStyle = '#aaaaaa';
    ctx.fillRect(76, 76, 48, 48);
  }
  ctx.fillStyle = '#aaaaaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Native gbitmap_sequence', 100, 170);
});
