// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = null;
var s1 = true;

var _data = [];

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '24px Gothic';

  // List items
  var _start = 0;
  for (var _i = 0; _i < 3; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#c0c0c0';
      ctx.font = '24px Gothic';
      ctx.textAlign = 'center';
      ctx.fillText('' + _item, 100, 100 + _i * 24 - _start * 24);
    }
  }
});

// Phone → watch data
rocky.on('message', function(event) {
  var data = event.data;
  if (data && data['items']) {
    try {
      _data = JSON.parse(data['items']);
      rocky.requestDraw();
    } catch (e) { console.log('Parse error: ' + e.message); }
  }
});

rocky.postMessage({'ready': true});
