// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ff0000';
  ctx.rockyFillRadial(90, 70, 0, 40, 0, 2 * Math.PI);
  ctx.fillStyle = '#0000ff';
  ctx.rockyFillRadial(150, 70, 0, 40, 0, 2 * Math.PI);
  ctx.fillStyle = '#00ff00';
  ctx.rockyFillRadial(110, 130, 0, 30, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getSeconds()), 100, 180);
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
