// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('64 Colors', 4, 4);
  ctx.fillStyle = '#404040';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'right';
  ctx.fillText("" + s0, 196, 6);
  ctx.fillStyle = '#000000';
  ctx.fillRect(4, 32, 44, 28);
  ctx.fillStyle = '#000055';
  ctx.fillRect(52, 32, 44, 28);
  ctx.fillStyle = '#0000aa';
  ctx.fillRect(100, 32, 44, 28);
  ctx.fillStyle = '#0000ff';
  ctx.fillRect(148, 32, 44, 28);
  ctx.fillStyle = '#005500';
  ctx.fillRect(4, 64, 44, 28);
  ctx.fillStyle = '#005555';
  ctx.fillRect(52, 64, 44, 28);
  ctx.fillStyle = '#0055aa';
  ctx.fillRect(100, 64, 44, 28);
  ctx.fillStyle = '#0055ff';
  ctx.fillRect(148, 64, 44, 28);
  ctx.fillStyle = '#00aa00';
  ctx.fillRect(4, 96, 44, 28);
  ctx.fillStyle = '#00aa55';
  ctx.fillRect(52, 96, 44, 28);
  ctx.fillStyle = '#00aaaa';
  ctx.fillRect(100, 96, 44, 28);
  ctx.fillStyle = '#00aaff';
  ctx.fillRect(148, 96, 44, 28);
  ctx.fillStyle = '#00ff00';
  ctx.fillRect(4, 128, 44, 28);
  ctx.fillStyle = '#00ff55';
  ctx.fillRect(52, 128, 44, 28);
  ctx.fillStyle = '#00ffaa';
  ctx.fillRect(100, 128, 44, 28);
  ctx.fillStyle = '#00ffff';
  ctx.fillRect(148, 128, 44, 28);
  ctx.fillStyle = '#550000';
  ctx.fillRect(4, 160, 44, 28);
  ctx.fillStyle = '#550055';
  ctx.fillRect(52, 160, 44, 28);
  ctx.fillStyle = '#5500aa';
  ctx.fillRect(100, 160, 44, 28);
  ctx.fillStyle = '#5500ff';
  ctx.fillRect(148, 160, 44, 28);
  ctx.fillStyle = '#555500';
  ctx.fillRect(4, 192, 44, 28);
  ctx.fillStyle = '#404040';
  ctx.fillRect(52, 192, 44, 28);
  ctx.fillStyle = '#5555aa';
  ctx.fillRect(100, 192, 44, 28);
  ctx.fillStyle = '#5555ff';
  ctx.fillRect(148, 192, 44, 28);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('UP/DOWN to scroll', 100, 210);
});
