// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#aaaaaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('System Gothic 14', 100, 20);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('ROBOTO_24', 100, 60);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('HELLO WORLD', 100, 100);
  ctx.fillStyle = '#aaaaaa';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('System Gothic 18 Bold', 100, 160);
});
