// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 24, 180, 64);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 100, 32);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Thu 15', 100, 72);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 100, 180, 36);
  ctx.fillStyle = '#00ff00';
  ctx.rockyFillRadial(28, 118, 0, 10, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Battery: 100%', 42, 110);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 140, 180, 36);
  ctx.fillStyle = '#0000ff';
  ctx.rockyFillRadial(28, 158, 0, 10, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Connected', 42, 150);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Pebble Dashboard — react-pebble', 100, 195);
});

rocky.on('minutechange', function(event) {
  rocky.requestDraw();
});
