// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;
var s1 = ["Buy groceries","Call dentist","Fix bike tire","Read chapter 5","Send invoice"];
var s2 = "";

rocky.on('draw', function(event) {
  var ctx = event.context;

  if (s2 === "") {
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#404040';
    ctx.fillRect(0, 0, 200, 28);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Notes (5)', 8, 4);
    ctx.fillStyle = '#0000ff';
    ctx.fillRect(0, 32, 170, 28);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 34);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Buy groceries', 24, 34);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 64);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Call dentist', 24, 64);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 94);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Fix bike tire', 24, 94);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 124);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Read chapter 5', 24, 124);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 154);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Send invoice', 24, 154);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('No save file', 4, 210);
  }
  else if (s2 === "__PROBE__") {
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#404040';
    ctx.fillRect(0, 0, 200, 28);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Notes (5)', 8, 4);
    ctx.fillStyle = '#00ff00';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('__PROBE__', 120, 6);
    ctx.fillStyle = '#0000ff';
    ctx.fillRect(0, 32, 170, 28);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 34);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Buy groceries', 24, 34);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 64);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Call dentist', 24, 64);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 94);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Fix bike tire', 24, 94);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 124);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Read chapter 5', 24, 124);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('○', 4, 154);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Send invoice', 24, 154);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('No save file', 4, 210);
  }
});
