// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = null;
var s1 = false;
var s2 = null;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('GPS Location', 100, 24);
  ctx.fillStyle = '#00ff00';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(s1 ? "Acquiring fix..." : "Location acquired", 100, 56);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 80, 180, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Latitude', 18, 84);
  ctx.fillStyle = '#00ffff';
  ctx.font = '28px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('--°', 18, 100);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 138, 180, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Longitude', 18, 142);
  ctx.fillStyle = '#00ffff';
  ctx.font = '28px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('--°', 18, 158);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Press SELECT to refresh', 100, 200);
});
