// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

var s3 = [];

rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 100, 10);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 70, 85, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Steps', 52, 72);
  ctx.fillStyle = '#00ffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('5432', 52, 88);
  ctx.fillStyle = '#404040';
  ctx.fillRect(105, 70, 85, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Distance', 147, 72);
  ctx.fillStyle = '#00ff00';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('3.8km', 147, 88);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 130, 85, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Calories', 52, 132);
  ctx.fillStyle = '#ff8000';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('210', 52, 148);
  ctx.fillStyle = '#404040';
  ctx.fillRect(105, 130, 85, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Heart', 147, 132);
  ctx.fillStyle = '#ff0000';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('72', 147, 148);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Sleep: 7h 0m', 100, 195);
});

rocky.on('minutechange', function(event) {
  rocky.requestDraw();
});
