// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 144, 168);
  ctx.fillStyle = '#000000';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Na na na na na na na na', 72, 139);
});
