// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = "list";
var s1 = 0;

var _data = [{"key":"PROJ-1","summary":"Fix login timeout","status":"In Progress"},{"key":"PROJ-2","summary":"Update dependencies","status":"To Do"},{"key":"PROJ-3","summary":"Add dark mode","status":"In Review"},{"key":"PROJ-4","summary":"API rate limiting","status":"In Progress"},{"key":"PROJ-5","summary":"Refactor auth","status":"To Do"}];

rocky.on('draw', function(event) {
  var ctx = event.context;

  if (s0 === "list") {
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, 200, 28);
    ctx.fillStyle = '#000000';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('JIRA Issues', 4, 4);
    ctx.fillStyle = '#404040';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'right';
    ctx.fillText((s1 + 1) + "/5", 196, 4);
    ctx.fillStyle = '#404040';
    ctx.fillRect(0, 0, 200, 60);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.fillStyle = '#00ffff';
    ctx.font = '14px Gothic';
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 60);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.fillStyle = '#00ffff';
    ctx.font = '14px Gothic';
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 60);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.fillStyle = '#00ffff';
    ctx.font = '14px Gothic';
  }
  else if (s0 === "detail") {
    ctx.fillStyle = '#0000ff';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('PROJ-1', 100, 8);
    ctx.fillStyle = '#ffffff';
    ctx.font = '24px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Fix login timeout', 10, 50);
    ctx.fillStyle = '#00ff00';
    ctx.beginPath();
    ctx.arc(18, 118, 8, 0, 2 * Math.PI, false);
    ctx.fill();
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('In Progress', 30, 106);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('BACK to return', 100, 200);
  }

  // List items
  var _start = s1;
  for (var _i = 0; _i < 3; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#ffffff';
      ctx.font = '18px bold Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.key || '', 8, 4 + _i * 0 - _start * 0);
      ctx.fillStyle = '#c0c0c0';
      ctx.font = '14px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.summary || '', 8, 26 + _i * 0 - _start * 0);
      ctx.fillStyle = '#00ffff';
      ctx.font = '14px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.status || '', 8, 42 + _i * 0 - _start * 0);
    }
  }
});
