// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Layout Demo', 100, 4);
  ctx.fillStyle = '#ff0000';
  ctx.beginPath();
  ctx.arc(16, 16, 16, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#00ff00';
  ctx.beginPath();
  ctx.arc(64, 16, 16, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#0000ff';
  ctx.beginPath();
  ctx.arc(112, 16, 16, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#ffff00';
  ctx.beginPath();
  ctx.arc(160, 16, 16, 0, 2 * Math.PI, false);
  ctx.fill();
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 0, 180, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('First Card', 8, 6);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 72, 180, 30);
  ctx.fillStyle = '#00ffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Second Card', 8, 6);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 144, 180, 30);
  ctx.fillStyle = '#ff8000';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Third Card', 8, 6);
});
