// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Layout Demo', 100, 4);
  ctx.fillStyle = '#ff0000';
  ctx.rockyFillRadial(36, 44, 0, 16, 0, 2 * Math.PI);
  ctx.fillStyle = '#00ff00';
  ctx.rockyFillRadial(84, 44, 0, 16, 0, 2 * Math.PI);
  ctx.fillStyle = '#0000ff';
  ctx.rockyFillRadial(132, 44, 0, 16, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffff00';
  ctx.rockyFillRadial(180, 44, 0, 16, 0, 2 * Math.PI);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 68, 180, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('First Card', 18, 74);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 104, 180, 30);
  ctx.fillStyle = '#00ffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Second Card', 18, 110);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 140, 180, 30);
  ctx.fillStyle = '#ff8000';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Third Card', 18, 146);
});
