// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;
var s1 = "";

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 0, 200, 26);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Settings', 4, 4);
  ctx.fillStyle = (s0 !== 0) ? 'black' : 'cyan';
  ctx.fillRect(0, 26, 200, 40);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Notifications', 8, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Manage alerts', 8, 48);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 66, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Display', 8, 68);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Brightness & theme', 8, 88);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 106, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Bluetooth', 8, 108);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Connected', 8, 128);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 146, 200, 26);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('About', 4, 150);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 172, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Version', 8, 174);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('v2.1.0', 8, 194);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 212, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Model', 8, 214);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Pebble Time 2', 8, 234);
});
