// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = "home";

rocky.on('draw', function(event) {
  var ctx = event.context;

  if (s0 === "home") {
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.font = '24px bold Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('Home', 100, 40);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('UP=Settings DOWN=About', 100, 100);
  }
  else if (s0 === "settings") {
    ctx.fillStyle = '#0000ff';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.font = '24px bold Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('Settings', 100, 40);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Brightness: 80%', 10, 100);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('SELECT for home', 100, 200);
  }
  else if (s0 === "about") {
    ctx.fillStyle = '#404040';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.font = '24px bold Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('About', 100, 40);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('react-pebble v0.1', 10, 100);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Compiled to piu', 10, 130);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('SELECT for home', 100, 200);
  }
});
