// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = 0;
var s1 = 0;
var s2 = "idle";
var s3 = false;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Multi-Click', 4, 4);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Double-click SELECT:', 100, 40);
  ctx.fillStyle = '#00ffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText("" + s0, 100, 58);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Hold UP (repeat):', 100, 95);
  ctx.fillStyle = '#00ff00';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText("" + s1, 100, 113);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('DOWN = 2s timer:', 100, 155);
  ctx.fillStyle = '#ffff00';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText("" + s2, 100, 173);
});
