// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = true;
var s1 = true;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#0000ff';
  ctx.fillRect(0, 0, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Header', 100, 8);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Main Content', 100, 100);
  ctx.fillStyle = '#00ff00';
  ctx.fillRect(0, 188, 200, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Footer', 100, 196);
});
