// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 15;
var s1 = false;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(s1 ? "Timer set to" : "Set Timer (min)", 100, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText("" + s0, 100, 85);
  ctx.fillStyle = '#404040';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(s1 ? "minutes" : "UP/DOWN to adjust", 100, 150);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(s1 ? "BACK to reset" : "SELECT to confirm", 100, 180);
});
