// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Path / Polygon', 4, 4);
  ctx.fillStyle = '#ffffff';
  ctx.rockyFillRadial(100, 100, 0, 3, 0, 2 * Math.PI);
  ctx.fillStyle = '#ff0000';
  ctx.fillRect(95, 50, 10, 50);
  ctx.fillStyle = '#00ffff';
  ctx.fillRect(10, 160, 60, 40);
  ctx.fillStyle = '#ffff00';
  ctx.fillRect(140, 170, 40, 30);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText("" + s0, 100, 205);
});
