// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 144, 168);
  ctx.fillStyle = '#404040';
  ctx.rockyFillRadial(72, 72, 0, 68, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(72, 9, 3, 10);
  ctx.fillStyle = '#c0c0c0';
  ctx.fillRect(125, 72, 10, 3);
  ctx.fillStyle = '#c0c0c0';
  ctx.fillRect(72, 125, 3, 10);
  ctx.fillStyle = '#c0c0c0';
  ctx.fillRect(9, 72, 10, 3);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(68, 38, 8, 34);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(69, 24, 6, 48);
  ctx.fillStyle = '#ffffff';
  ctx.rockyFillRadial(72, 72, 0, 4, 0, 2 * Math.PI);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 72, 140);
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
