// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

var _data = [{"title":"Fix login bug","status":"In Progress"},{"title":"Update docs","status":"To Do"},{"title":"Deploy v2","status":"Done"},{"title":"API rate limit","status":"In Progress"},{"title":"Refactor auth","status":"To Do"}];

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Issues', 4, 4);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';

  // List items
  var _start = s0;
  for (var _i = 0; _i < 3; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#ffffff';
      ctx.font = '18px bold Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.title || '', 8, 4 + _i * 0 - _start * 0);
      ctx.fillStyle = '#c0c0c0';
      ctx.font = '14px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.status || '', 8, 26 + _i * 0 - _start * 0);
    }
  }
});
