// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(8, 8, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Round Safe', 12, 12);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('This content is', 8, 48);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('inset to avoid', 8, 68);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('round edges.', 8, 88);
  ctx.fillStyle = '#404040';
  ctx.fillRect(8, 118, 180, 36);
  ctx.fillStyle = '#00ffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Display: 136x160 (rect)', 12, 126);
  ctx.fillStyle = '#404040';
  ctx.fillRect(8, 160, 180, 36);
  ctx.fillStyle = '#00ffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Offset: x=4 y=4', 12, 168);
});
