// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

var _data = ["Introduction","Getting Started","Installation","Configuration","Components","Hooks","Animation","Sensors","Networking","Storage","Deployment","Troubleshooting"];

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 144, 168);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 144, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText("Docs (" + (s0 + 1) + "-" + MIN(s0 + 4, 12) + "/12)", 4, 4);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 28, 144, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 60, 144, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 92, 144, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 124, 144, 30);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.fillStyle = '#00ffff';
  ctx.fillRect(62, 165, 20, 3);

  // List items
  var _start = s0;
  for (var _i = 0; _i < 4; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#ffffff';
      ctx.font = '18px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText('' + _item, 10, 34 + _i * 32 - _start * 32);
    }
  }
});
