// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

var _data = [{"title":"Fix login bug","tag":"HIGH"},{"title":"Update docs","tag":"MED"},{"title":"Deploy v2","tag":"LOW"},{"title":"API rate limit","tag":"HIGH"},{"title":"Refactor auth","tag":"MED"}];

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 30);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Tasks', 4, 5);
  ctx.fillStyle = '#404040';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'right';
  ctx.fillText((s0 + 1) + "/5", 196, 5);
  ctx.fillStyle = '#404040';
  ctx.fillRect(0, 34, 200, 58);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 94, 200, 58);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 154, 200, 58);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';

  // List items
  var _start = s0;
  for (var _i = 0; _i < 3; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#ffffff';
      ctx.font = '18px bold Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.title || '', 8, 6 + _i * 0 - _start * 0);
      ctx.fillStyle = '#c0c0c0';
      ctx.font = '14px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText(_item.tag || '', 8, 30 + _i * 0 - _start * 0);
    }
  }
});
