// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;
var s1 = 18;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Settings', 85, 8);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 44, 160, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Theme (SELECT to cycle)', 18, 48);
  ctx.fillStyle = '#00ffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('dark', 18, 66);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 102, 160, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Font Size (UP/DOWN)', 18, 106);
  ctx.fillStyle = '#00ffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText("" + s1, 18, 124);
  ctx.fillStyle = '#404040';
  ctx.fillRect(10, 160, 160, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Preview', 18, 164);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Hello Pebble!', 18, 182);
});
