// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = "None";
var s1 = 0;
var s2 = 0;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Simple Menu', 4, 4);
  ctx.fillStyle = (s1 !== 0) ? 'black' : 'cyan';
  ctx.fillRect(0, 0, 200, 36);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Inbox', 8, 2);
  ctx.fillStyle = '#000000';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('3 new messages', 8, 20);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 36, 200, 36);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Sent', 8, 38);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('12 items', 8, 56);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 72, 200, 36);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Drafts', 8, 74);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('1 draft', 8, 92);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 108, 200, 36);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Trash', 8, 116);
  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 144, 200, 36);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Settings', 8, 152);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText("" + s0, 100, 200);
});
