// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;

var _data = ["Alpha","Beta","Gamma","Delta","Epsilon"];

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Items', 100, 4);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Gothic';
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Gothic';
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Gothic';

  // List items
  var _start = s0;
  for (var _i = 0; _i < 3; _i++) {
    var _item = _data[_start + _i];
    if (_item !== undefined) {
      ctx.fillStyle = '#ffffff';
      ctx.font = '24px Gothic';
      ctx.textAlign = 'left';
      ctx.fillText('' + _item, 10, 40 + _i * 50 - _start * 50);
    }
  }
});
