// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = false;
var s1 = 0;
var s2 = 0;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Smartstrap', 100, 12);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText(s0 ? "Available: yes" : "Available: no", 4, 50);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText("" + s1, 4, 80);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('UP: read', 4, 130);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('DOWN: write 0x42', 4, 154);
});
