// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

var s0 = false;
var s1 = "00:00";
var _startTime_s0 = Date.now();

rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = s0 ? 'green' : 'black';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#404040';
  ctx.rockyFillRadial(100, 84, 0, 60, 0, 2 * Math.PI);
  ctx.fillStyle = '#000000';
  ctx.rockyFillRadial(100, 84, 0, 56, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(s0 ? (function(e) { return pad(Math.floor(e / 60)) + ":" + pad(e % 60); })(Math.floor((Date.now() - _startTime_s0) / 1000)) : "00:00", 100, 55);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(s0 ? "RUNNING" : "STOPPED", 100, 160);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('SELECT start/stop · DOWN reset', 100, 200);
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
