// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, 200, 28);
  ctx.fillStyle = '#000000';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Text Flow', 4, 4);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('The Pebble smartwatch was a groundbreaking device that proved wearable technology could be both functional and stylish. With its e-paper display and week-long battery life, it changed how people thought about wrist computers. Now with Alloy, the spirit lives on.', 10, 36);
});
