// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Timeline Pins', 100, 8);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('SELECT: push demo pin', 4, 56);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('DOWN: remove pin', 4, 96);
});
