// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = null;
var s1 = null;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Subscriptions', 100, 8);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Topics:', 4, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('(loading)', 4, 60);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('UP: subscribe "news"', 4, 110);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('DOWN: unsubscribe "news"', 4, 134);
  ctx.fillStyle = '#ffaa55';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('SELECT: refresh list', 4, 158);
});
