// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = false;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = s0 ? 'green' : 'red';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(s0 ? "ON" : "OFF", 100, 90);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('SELECT to toggle', 100, 180);
});
