// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

var s0 = null;
var s1 = null;
var s2 = null;
var s3 = null;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('Identity Tokens', 100, 8);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Account:', 4, 40);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('(loading)', 4, 58);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Watch:', 4, 86);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('(loading)', 4, 104);
  ctx.fillStyle = '#aaffaa';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Timeline:', 4, 132);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('(loading)', 4, 150);
});
