// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = 0;
var s1 = "list";

rocky.on('draw', function(event) {
  var ctx = event.context;

  if (s1 === "list") {
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#404040';
    ctx.fillRect(0, 0, 200, 28);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Central Stn', 8, 4);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'right';
    ctx.fillText("" + s0, 192, 6);
    ctx.fillStyle = '#404040';
    ctx.fillRect(4, 34, 192, 58);
    ctx.fillStyle = '#ff0000';
    ctx.rockyFillRadial(22, 59, 0, 12, 0, 2 * Math.PI);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 40);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 62);
    ctx.fillStyle = '#00ffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'right';
    ctx.fillText("" + s0, 192, 44);
    ctx.fillStyle = '#000000';
    ctx.fillRect(4, 98, 192, 58);
    ctx.fillStyle = '#0000ff';
    ctx.rockyFillRadial(22, 123, 0, 12, 0, 2 * Math.PI);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 104);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 126);
    ctx.fillStyle = '#00ffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'right';
    ctx.fillText("" + s0, 192, 108);
    ctx.fillStyle = '#000000';
    ctx.fillRect(4, 162, 192, 58);
    ctx.fillStyle = '#00ff00';
    ctx.rockyFillRadial(22, 187, 0, 12, 0, 2 * Math.PI);
    ctx.fillStyle = '#ffffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 168);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText("" + s0, 40, 190);
    ctx.fillStyle = '#00ffff';
    ctx.font = '18px bold Gothic';
    ctx.textAlign = 'right';
    ctx.fillText("" + s0, 192, 172);
  }
  else if (s1 === "detail") {
    ctx.fillStyle = '#0000ff';
    ctx.fillRect(0, 0, 200, 228);
    ctx.fillStyle = '#ffffff';
    ctx.font = '28px bold Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('F-Line', 100, 10);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('West to Beach', 100, 44);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(20, 64, 160, 1);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'left';
    ctx.fillText('Next departure:', 10, 74);
    ctx.fillStyle = '#ffffff';
    ctx.font = '42px bold Bitham';
    ctx.textAlign = 'left';
    ctx.fillText('2 min', 20, 96);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(20, 160, 160, 1);
    ctx.fillStyle = '#c0c0c0';
    ctx.font = '14px Gothic';
    ctx.textAlign = 'center';
    ctx.fillText('BACK to return', 100, 200);
  }
});
