// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

// WARNING: Rocky.js on basalt does not support button events.
// Interactive features (buttons, scrolling) will not work.

var s0 = false;

rocky.on('draw', function(event) {
  var ctx = event.context;

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px bold Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('List View', 100, 20);
  ctx.fillStyle = '#ffffff';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Item 1', 10, 60);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText('SELECT for detail', 100, 200);
});
