// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(8, 24, 184, 1);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 100, 50);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '24px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getSeconds()), 100, 110);
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(8, 150, 184, 1);
  ctx.fillStyle = '#ffffff';
  ctx.font = '24px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(days[d.getDay()] + " " + months[d.getMonth()] + " " + d.getDate(), 100, 160);
});

rocky.on('secondchange', function(event) {
  rocky.requestDraw();
});
