// Auto-generated by react-pebble (Rocky.js backend for classic Pebble)
//
// Target: basalt (144x168)

var rocky = require('rocky');

function pad(n) { return n < 10 ? "0" + n : "" + n; }
var days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];


rocky.on('draw', function(event) {
  var ctx = event.context;
  var d = new Date();

  ctx.fillStyle = '#000000';
  ctx.fillRect(0, 0, 200, 228);
  ctx.fillStyle = '#ffffff';
  ctx.font = '42px bold Bitham';
  ctx.textAlign = 'center';
  ctx.fillText(pad(d.getHours()) + ":" + pad(d.getMinutes()), 100, 8);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '18px Gothic';
  ctx.textAlign = 'center';
  ctx.fillText(days[d.getDay()] + " " + months[d.getMonth()] + " " + d.getDate(), 100, 55);
  ctx.fillStyle = '#404040';
  ctx.fillRect(20, 80, 160, 1);
  ctx.fillStyle = '#ffff00';
  ctx.rockyFillRadial(40, 110, 0, 20, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '28px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('72°F', 70, 90);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Sunny', 70, 118);
  ctx.fillStyle = '#404040';
  ctx.fillRect(20, 142, 160, 1);
  ctx.fillStyle = '#ffff00';
  ctx.rockyFillRadial(18, 164, 0, 8, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Thu', 32, 152);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('75°/58°', 80, 152);
  ctx.fillStyle = '#c0c0c0';
  ctx.rockyFillRadial(18, 188, 0, 8, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Fri', 32, 176);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('68°/52°', 80, 176);
  ctx.fillStyle = '#00ffff';
  ctx.rockyFillRadial(18, 212, 0, 8, 0, 2 * Math.PI);
  ctx.fillStyle = '#ffffff';
  ctx.font = '14px bold Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('Sat', 32, 200);
  ctx.fillStyle = '#c0c0c0';
  ctx.font = '14px Gothic';
  ctx.textAlign = 'left';
  ctx.fillText('62°/48°', 80, 200);
});

rocky.on('minutechange', function(event) {
  rocky.requestDraw();
});
