// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/analog-clock.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const sk2 = new Skin({ fill: "#c0c0c0" });
const sk3 = new Skin({ fill: "#ff0000" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "24px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "18px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.tl0 = c.content("tl0");
    this.tl1 = c.content("tl1");
  }
  onDisplaying(app) {
    this.refresh();
    this._tick = () => this.onTimeChanged();
    watch.addEventListener('secondchange', this._tick);
  }
  onTimeChanged() {
    this.refresh();
  }
  onUndisplaying(app) {
    if (this._tick) watch.removeEventListener('secondchange', this._tick);
  }
  refresh() {
    const d = new Date();
    if (this.tl0) this.tl0.string = pad(d.getHours()) + ":" + pad(d.getMinutes());
    if (this.tl1) this.tl1.string = pad(d.getSeconds());
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new RoundRect(null, { left: 92, top: 10, width: 16, height: 16, radius: 8, skin: sk1 }),
        new RoundRect(null, { left: 174, top: 98, width: 16, height: 16, radius: 8, skin: sk1 }),
        new RoundRect(null, { left: 92, top: 186, width: 16, height: 16, radius: 8, skin: sk1 }),
        new RoundRect(null, { left: 10, top: 98, width: 16, height: 16, radius: 8, skin: sk1 }),
        new RoundRect(null, { left: 134, top: 22, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 164, top: 54, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 164, top: 150, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 134, top: 182, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 50, top: 182, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 20, top: 150, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 20, top: 54, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 50, top: 22, width: 8, height: 8, radius: 4, skin: sk2 }),
        new RoundRect(null, { left: 90, top: 100, width: 24, height: 24, radius: 12, skin: sk3 }),
        new Label(null, { top: 68, left: 0, width: 200, style: st0, horizontal: "center", name: "tl0", string: "09:07" }),
        new Label(null, { top: 120, left: 0, width: 200, style: st1, horizontal: "center", name: "tl1", string: "03" }),
        new Label(null, { top: 155, left: 0, width: 200, style: st2, horizontal: "center", string: "Thu 15" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
