// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/animation.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const sk1 = new Skin({ fill: "#ff0000" });
const sk2 = new Skin({ fill: "#00ffff" });
const sk3 = new Skin({ fill: "#404040" });
const sk4 = new Skin({ fill: "#00ff00" });
const st1 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.s1 = true;
    this.s2 = 0;
    this.s3 = true;
    this.s4 = 0;
    this.s5 = true;
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    this.sl1.string = "" + this.s4;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 4, left: 0, width: 200, style: st0, horizontal: "center", string: "Animation Demo" }),
        new RoundRect(null, { left: 20, top: 10, width: 24, height: 24, radius: 12, skin: sk1 }),
        new RoundRect(null, { left: 100, top: 100, width: 10, height: 10, radius: 5, skin: sk2 }),
        new Content(null, { left: 10, width: 180, top: 200, height: 8, skin: sk3 }),
        new Content(null, { left: 10, width: 0, top: 200, height: 8, skin: sk4 }),
        new Label(null, { top: 212, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "0%" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
