// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/animated-apng.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const tex0 = new Texture("spinner.png");
const tsk0 = new Skin({ texture: tex0, x: 0, y: 0, width: 48, height: 48 });
const st1 = new Style({ font: "14px Gothic", color: "#aaaaaa" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 12, left: 0, width: 200, style: st0, horizontal: "center", string: "Animated APNG" }),
        new Content(null, { left: 76, width: 48, top: 76, height: 48, skin: tsk0 }),
        new Label(null, { top: 170, left: 0, width: 200, style: st1, horizontal: "center", string: "Native gbitmap_sequence" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
