// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/animation.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const sk1 = new Skin({ fill: "#ff0000" });
const sk2 = new Skin({ fill: "#00ffff" });
const sk3 = new Skin({ fill: "#404040" });
const sk4 = new Skin({ fill: "#00ff00" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.tl1 = c.content("tl1");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
  }
  onTimeChanged() {
    this.refresh();
  }
  refresh() {
    const d = new Date();
    this.tl1.string = pad(d.getMinutes()) + ":" + pad(d.getSeconds());
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 4, left: 0, width: 200, style: st0, horizontal: "center", string: "Animation Demo" }),
        new RoundRect(null, { left: 20, top: 153, width: 24, height: 24, radius: 12, skin: sk1 }),
        new RoundRect(null, { left: 130, top: 90, width: 60, height: 60, radius: 30, skin: sk2 }),
        new Content(null, { left: 10, width: 180, top: 190, height: 10, skin: sk3 }),
        new Content(null, { left: 10, width: 162, top: 190, height: 10, skin: sk4 }),
        new Label(null, { top: 205, left: 0, width: 200, style: st1, horizontal: "center", name: "tl1", string: "07:03" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
