// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/arc.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const sk2 = new Skin({ fill: "#404040" });
class _ab3 extends Behavior {
  onDraw(port, x, y, w, h) {
    const cx = 45, cy = 45, oR = 45, iR = 32;
    const sA = 0, eA = 360;
    const rSq = oR * oR, iSq = iR * iR;
    for (let dy = -oR; dy <= oR; dy++) {
      let ss = -1, sp = false;
      for (let dx = -oR; dx <= oR; dx++) {
        const d = dx*dx + dy*dy;
        if (d <= rSq && d >= iSq) {
          const a = (Math.atan2(dx, -dy) * 180 / Math.PI + 360) % 360;
          const s = ((sA%360)+360)%360, e = ((eA%360)+360)%360;
          const ok = s<=e ? (a>=s&&a<=e) : (a>=s||a<=e);
          if (ok) { if (!sp) { ss = cx+dx; sp = true; } }
          else if (sp) { port.drawSkin(sk2, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
        } else if (sp) { port.drawSkin(sk2, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
      }
      if (sp) port.drawSkin(sk2, ss, cy+dy, (cx+oR+1)-ss, 1);
    }
  }
}
const sk3 = new Skin({ fill: "#00ffff" });
class _ab25 extends Behavior {
  onDraw(port, x, y, w, h) {
    const cx = 45, cy = 45, oR = 45, iR = 32;
    const sA = 0, eA = 234;
    const rSq = oR * oR, iSq = iR * iR;
    for (let dy = -oR; dy <= oR; dy++) {
      let ss = -1, sp = false;
      for (let dx = -oR; dx <= oR; dx++) {
        const d = dx*dx + dy*dy;
        if (d <= rSq && d >= iSq) {
          const a = (Math.atan2(dx, -dy) * 180 / Math.PI + 360) % 360;
          const s = ((sA%360)+360)%360, e = ((eA%360)+360)%360;
          const ok = s<=e ? (a>=s&&a<=e) : (a>=s||a<=e);
          if (ok) { if (!sp) { ss = cx+dx; sp = true; } }
          else if (sp) { port.drawSkin(sk3, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
        } else if (sp) { port.drawSkin(sk3, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
      }
      if (sp) port.drawSkin(sk3, ss, cy+dy, (cx+oR+1)-ss, 1);
    }
  }
}
const st1 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const sk4 = new Skin({ fill: "#ff0000" });
class _ab48 extends Behavior {
  onDraw(port, x, y, w, h) {
    const cx = 30, cy = 30, oR = 30, iR = 0;
    const sA = 0, eA = 120;
    const rSq = oR * oR, iSq = iR * iR;
    for (let dy = -oR; dy <= oR; dy++) {
      let ss = -1, sp = false;
      for (let dx = -oR; dx <= oR; dx++) {
        const d = dx*dx + dy*dy;
        if (d <= rSq && d >= iSq) {
          const a = (Math.atan2(dx, -dy) * 180 / Math.PI + 360) % 360;
          const s = ((sA%360)+360)%360, e = ((eA%360)+360)%360;
          const ok = s<=e ? (a>=s&&a<=e) : (a>=s||a<=e);
          if (ok) { if (!sp) { ss = cx+dx; sp = true; } }
          else if (sp) { port.drawSkin(sk4, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
        } else if (sp) { port.drawSkin(sk4, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
      }
      if (sp) port.drawSkin(sk4, ss, cy+dy, (cx+oR+1)-ss, 1);
    }
  }
}
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk5 = new Skin({ fill: "#ffff00" });
class _ab71 extends Behavior {
  onDraw(port, x, y, w, h) {
    const cx = 30, cy = 30, oR = 30, iR = 0;
    const sA = 45, eA = 315;
    const rSq = oR * oR, iSq = iR * iR;
    const steps = Math.max(Math.round(2*Math.PI*oR*2), 60);
    const sR = (sA-90)*Math.PI/180, eR = (eA-90)*Math.PI/180;
    let tR = eR - sR; if (tR<=0) tR += 2*Math.PI;
    for (let i=0; i<=steps; i++) {
      const r = sR + (i/steps)*tR;
      port.drawSkin(sk5, Math.round(cx+oR*Math.cos(r)), Math.round(cy+oR*Math.sin(r)), 2, 2);
    }
  }
}
const sk6 = new Skin({ fill: "#00ff00" });
class _ab86 extends Behavior {
  onDraw(port, x, y, w, h) {
    const cx = 25, cy = 25, oR = 25, iR = 15;
    const sA = 0, eA = 270;
    const rSq = oR * oR, iSq = iR * iR;
    for (let dy = -oR; dy <= oR; dy++) {
      let ss = -1, sp = false;
      for (let dx = -oR; dx <= oR; dx++) {
        const d = dx*dx + dy*dy;
        if (d <= rSq && d >= iSq) {
          const a = (Math.atan2(dx, -dy) * 180 / Math.PI + 360) % 360;
          const s = ((sA%360)+360)%360, e = ((eA%360)+360)%360;
          const ok = s<=e ? (a>=s&&a<=e) : (a>=s||a<=e);
          if (ok) { if (!sp) { ss = cx+dx; sp = true; } }
          else if (sp) { port.drawSkin(sk6, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
        } else if (sp) { port.drawSkin(sk6, ss, cy+dy, (cx+dx)-ss, 1); sp = false; }
      }
      if (sp) port.drawSkin(sk6, ss, cy+dy, (cx+oR+1)-ss, 1);
    }
  }
}

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 65;
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 += 10; this.refresh(); }
    if (name === "down") { this.s0 -= 10; this.refresh(); }
    if (name === "select") { this.s0 = 0; this.refresh(); }
  }
  refresh() {
    if (this.sl1) this.sl1.string = "" + this.s0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
        new Label(null, { top: 4, left: 4, width: 192, style: st0, string: "Arc / Radial" }),
        new Port(null, { left: 55, top: 40, width: 90, height: 90, Behavior: _ab3 }),
        new Port(null, { left: 55, top: 40, width: 90, height: 90, Behavior: _ab25 }),
        new Label(null, { top: 68, left: 55, width: 90, style: st1, horizontal: "center", name: "sl1", string: "65%" }),
        new Port(null, { left: 10, top: 150, width: 60, height: 60, Behavior: _ab48 }),
        new Label(null, { top: 212, left: 10, width: 60, style: st2, horizontal: "center", string: "Pie" }),
        new Port(null, { left: 80, top: 150, width: 60, height: 60, Behavior: _ab71 }),
        new Label(null, { top: 212, left: 80, width: 60, style: st2, horizontal: "center", string: "Stroke" }),
        new Port(null, { left: 145, top: 155, width: 50, height: 50, Behavior: _ab86 }),
        new Label(null, { top: 212, left: 145, width: 50, style: st2, horizontal: "center", string: "Donut" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
