// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/async-list.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";

import Message from "pebble/message";

const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "24px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

let _data = [];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = null;
    this.s1 = true;
    this._ls = [];
    const _g0 = c.content("lg0");
    this._ls.push([_g0.content("ls0_0"), _g0.content("ls0_1")]);
    const _g1 = c.content("lg1");
    this._ls.push([_g1.content("ls1_0"), _g1.content("ls1_1")]);
    const _g2 = c.content("lg2");
    this._ls.push([_g2.content("ls2_0"), _g2.content("ls2_1")]);
  }
  onDisplaying(app) {
    const self = this;
    new Message({
      keys: ["items"],
      onReadable() {
        const map = this.read();
        const json = map.get("items");
        if (json) {
          try {
            _data = JSON.parse(json);
            const c = app.first;
            const g0 = c.content("lg0");
            if (g0) { const l = g0.content("ls0_0"); if (l) l.string = _data[0] ? Object.values(_data[0] || {})[0] || "" : ""; }
            if (g0) { const l = g0.content("ls0_1"); if (l) l.string = _data[0] ? Object.values(_data[0] || {})[1] || "" : ""; }
            const g1 = c.content("lg1");
            if (g1) { const l = g1.content("ls1_0"); if (l) l.string = _data[1] ? Object.values(_data[1] || {})[0] || "" : ""; }
            if (g1) { const l = g1.content("ls1_1"); if (l) l.string = _data[1] ? Object.values(_data[1] || {})[1] || "" : ""; }
            const g2 = c.content("lg2");
            if (g2) { const l = g2.content("ls2_0"); if (l) l.string = _data[2] ? Object.values(_data[2] || {})[0] || "" : ""; }
            if (g2) { const l = g2.content("ls2_1"); if (l) l.string = _data[2] ? Object.values(_data[2] || {})[1] || "" : ""; }
          } catch (e) { console.log("Parse error: " + e.message); }
        }
      }
    });
  }
  refresh() {
  }
  refreshList() {
    for (let i = 0; i < 3; i++) {
      const item = _data[i];
      if (this._ls[i]) {
        this._ls[i].string = item !== undefined ? "" + item : "";
        this._ls[i].visible = (item !== undefined);
      }
    }
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { name: "lg0", left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 100, left: 0, width: 200, style: st0, horizontal: "center", name: "ls0_0", string: "Loading..." })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
