// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/circles.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ff0000" });
const sk2 = new Skin({ fill: "#0000ff" });
const sk3 = new Skin({ fill: "#00ff00" });
const st0 = new Style({ font: "24px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.tl0 = c.content("tl0");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
  }
  onTimeChanged() {
    this.refresh();
  }
  refresh() {
    const d = new Date();
    if (this.tl0) this.tl0.string = pad(d.getSeconds());
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new RoundRect(null, { left: 50, top: 30, width: 80, height: 80, radius: 40, skin: sk1 }),
        new RoundRect(null, { left: 110, top: 30, width: 80, height: 80, radius: 40, skin: sk2 }),
        new RoundRect(null, { left: 80, top: 100, width: 60, height: 60, radius: 30, skin: sk3 }),
        new Label(null, { top: 180, left: 0, width: 200, style: st0, horizontal: "center", name: "tl0", string: "03" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
