// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/color-palette.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "14px Gothic", color: "#404040" });
const sk2 = new Skin({ fill: "#000055" });
const sk3 = new Skin({ fill: "#0000aa" });
const sk4 = new Skin({ fill: "#0000ff" });
const sk5 = new Skin({ fill: "#005500" });
const sk6 = new Skin({ fill: "#005555" });
const sk7 = new Skin({ fill: "#0055aa" });
const sk8 = new Skin({ fill: "#0055ff" });
const sk9 = new Skin({ fill: "#00aa00" });
const sk10 = new Skin({ fill: "#00aa55" });
const sk11 = new Skin({ fill: "#00aaaa" });
const sk12 = new Skin({ fill: "#00aaff" });
const sk13 = new Skin({ fill: "#00ff00" });
const sk14 = new Skin({ fill: "#00ff55" });
const sk15 = new Skin({ fill: "#00ffaa" });
const sk16 = new Skin({ fill: "#00ffff" });
const sk17 = new Skin({ fill: "#550000" });
const sk18 = new Skin({ fill: "#550055" });
const sk19 = new Skin({ fill: "#5500aa" });
const sk20 = new Skin({ fill: "#5500ff" });
const sk21 = new Skin({ fill: "#555500" });
const sk22 = new Skin({ fill: "#404040" });
const sk23 = new Skin({ fill: "#5555aa" });
const sk24 = new Skin({ fill: "#5555ff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "down") { this.s0 += 1; this.refresh(); }
    if (name === "up") { this.s0 -= 1; this.refresh(); }
  }
  refresh() {
    if (this.sl1) this.sl1.string = "" + this.s0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
        new Label(null, { top: 4, left: 4, width: 140, style: st0, string: "64 Colors" }),
        new Label(null, { top: 6, left: 140, width: 56, style: st1, horizontal: "right", name: "sl1", string: "1/3" }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 32, height: 28, skin: sk0 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 32, height: 28, skin: sk2 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 32, height: 28, skin: sk3 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 32, height: 28, skin: sk4 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 64, height: 28, skin: sk5 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 64, height: 28, skin: sk6 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 64, height: 28, skin: sk7 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 64, height: 28, skin: sk8 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 96, height: 28, skin: sk9 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 96, height: 28, skin: sk10 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 96, height: 28, skin: sk11 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 96, height: 28, skin: sk12 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 128, height: 28, skin: sk13 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 128, height: 28, skin: sk14 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 128, height: 28, skin: sk15 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 128, height: 28, skin: sk16 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 160, height: 28, skin: sk17 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 160, height: 28, skin: sk18 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 160, height: 28, skin: sk19 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 160, height: 28, skin: sk20 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 4, width: 44, top: 192, height: 28, skin: sk21 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 52, width: 44, top: 192, height: 28, skin: sk22 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 100, width: 44, top: 192, height: 28, skin: sk23 })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 148, width: 44, top: 192, height: 28, skin: sk24 })
        ] }),
        new Label(null, { top: 210, left: 0, width: 200, style: st2, horizontal: "center", string: "UP/DOWN to scroll" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
