// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/compass.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const sk2 = new Skin({ fill: "#ff0000" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "24px Gothic", color: "#00ffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.s1 = 0;
    this.s2 = "calibrated";
    this.sl0 = c.content("sl0");
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl0) this.sl0.string = "" + this.s0;
    if (this.sl1) this.sl1.string = "" + this.s0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new RoundRect(null, { left: 96, top: 96, width: 8, height: 8, radius: 4, skin: sk1 }),
        new Content(null, { left: 100, top: 40, width: 2, height: 60, skin: sk2 }),
        new Label(null, { top: 170, left: 0, width: 200, style: st0, horizontal: "center", name: "sl0", string: "0°" }),
        new Label(null, { top: 200, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "N" }),
        new Label(null, { top: 28, left: 0, width: 200, style: st2, horizontal: "center", string: "tilt: x=0 y=0" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
