// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/config-rich.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 40, left: 0, width: 200, style: st0, horizontal: "center", string: "Hi Friend" }),
        new Label(null, { top: 90, left: 0, width: 200, style: st1, horizontal: "center", string: "run · metric" }),
        new Label(null, { top: 130, left: 0, width: 200, style: st2, horizontal: "center", string: "pace, hr" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
