// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/counter.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 += 1; this.refresh(); }
    if (name === "down") { this.s0 -= 1; this.refresh(); }
    if (name === "select") { this.s0 = 0; this.refresh(); }
  }
  refresh() {
    if (this.sl1) this.sl1.string = "" + this.s0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 0, right: 0, top: 0, height: 32, skin: sk1 }),
        new Label(null, { top: 6, left: 4, width: 192, style: st0, string: "Counter" }),
        new Label(null, { top: 70, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "0" }),
        new Label(null, { top: 170, left: 0, width: 200, style: st2, horizontal: "center", string: "UP/DOWN to count" }),
        new Label(null, { top: 190, left: 0, width: 200, style: st2, horizontal: "center", string: "SELECT to reset" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
