// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/custom-font.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "14px Gothic", color: "#aaaaaa" });
const st1 = new Style({ font: "24px Gothic", color: "#ffaa55" });
const st2 = new Style({ font: "24px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "bold 18px Gothic", color: "#aaaaaa" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "System Gothic 14" }),
        new Label(null, { top: 60, left: 0, width: 200, style: st1, horizontal: "center", string: "ROBOTO_24" }),
        new Label(null, { top: 100, left: 0, width: 200, style: st2, horizontal: "center", string: "HELLO WORLD" }),
        new Label(null, { top: 160, left: 0, width: 200, style: st3, horizontal: "center", string: "System Gothic 18 Bold" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
