// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/dashboard.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#404040" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk2 = new Skin({ fill: "#00ff00" });
const st2 = new Style({ font: "18px Gothic", color: "#ffffff" });
const sk3 = new Skin({ fill: "#0000ff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.tl0 = c.content("tl0");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
  }
  onTimeChanged() {
    this.refresh();
  }
  refresh() {
    const d = new Date();
    this.tl0.string = pad(d.getHours()) + ":" + pad(d.getMinutes());
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 10, width: 180, top: 24, height: 64, skin: sk1 }),
        new Label(null, { top: 32, left: 10, width: 180, style: st0, horizontal: "center", name: "tl0", string: "09:07" }),
        new Label(null, { top: 72, left: 10, width: 180, style: st1, horizontal: "center", string: "Thu 15" }),
        new Container(null, { left: 10, right: 0, top: 100, contents: [
          new Content(null, { left: 0, width: 180, top: 0, height: 36, skin: sk1 }),
          new Container(null, { left: 0, right: 0, top: 40, contents: [
            new RoundRect(null, { left: 8, top: 8, width: 20, height: 20, radius: 10, skin: sk2 }),
            new Label(null, { top: 10, left: 32, width: 140, style: st2, string: "Battery: 100%" })
          ] }),
          new Content(null, { left: 0, width: 180, top: 80, height: 36, skin: sk1 }),
          new Container(null, { left: 0, right: 0, top: 120, contents: [
            new RoundRect(null, { left: 8, top: 8, width: 20, height: 20, radius: 10, skin: sk3 }),
            new Label(null, { top: 10, left: 32, width: 140, style: st2, string: "Connected" })
          ] })
        ] }),
        new Label(null, { top: 195, left: 10, width: 180, style: st1, horizontal: "center", string: "Pebble Dashboard — react-pebble" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
