// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/file-notes.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#404040" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const sk2 = new Skin({ fill: "#0000ff" });
const st1 = new Style({ font: "bold 18px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st4 = new Style({ font: "14px Gothic", color: "#00ff00" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.content("br_s2_v0").first;
    this.s0 = 0;
    this.s1 = ["Buy groceries","Call dentist","Fix bike tire","Read chapter 5","Send invoice"];
    this.s2 = "";
    this.br_s2_v0 = app.content("br_s2_v0");
    this.br_s2_v1 = app.content("br_s2_v1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 -= 1; this.refresh(); }
  }
  refresh() {
    this.br_s2_v0.visible = (this.s2 === "");
    this.br_s2_v1.visible = (this.s2 === "__PROBE__");
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
    new Container(null, { name: "br_s2_v0", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
          new Label(null, { top: 4, left: 8, width: 160, style: st0, string: "Notes (5)" }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, width: 170, top: 32, height: 28, skin: sk2 }),
            new Label(null, { top: 34, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 34, left: 24, width: 140, style: st2, string: "Buy groceries" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 64, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 64, left: 24, width: 140, style: st2, string: "Call dentist" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 94, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 94, left: 24, width: 140, style: st2, string: "Fix bike tire" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 124, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 124, left: 24, width: 140, style: st2, string: "Read chapter 5" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 154, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 154, left: 24, width: 140, style: st2, string: "Send invoice" })
          ] }),
          new Label(null, { top: 210, left: 4, width: 166, style: st3, string: "No save file" })
        ] })
    ] }),
    new Container(null, { name: "br_s2_v1", visible: false, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
          new Label(null, { top: 4, left: 8, width: 160, style: st0, string: "Notes (5)" }),
          new Label(null, { top: 6, left: 120, width: 50, style: st4, string: "__PROBE__" }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, width: 170, top: 32, height: 28, skin: sk2 }),
            new Label(null, { top: 34, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 34, left: 24, width: 140, style: st2, string: "Buy groceries" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 64, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 64, left: 24, width: 140, style: st2, string: "Call dentist" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 94, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 94, left: 24, width: 140, style: st2, string: "Fix bike tire" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 124, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 124, left: 24, width: 140, style: st2, string: "Read chapter 5" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Label(null, { top: 154, left: 4, width: 20, style: st1, string: "○" }),
            new Label(null, { top: 154, left: 24, width: 140, style: st2, string: "Send invoice" })
          ] }),
          new Label(null, { top: 210, left: 4, width: 166, style: st3, string: "No save file" })
        ] })
    ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
