// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/gps.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "14px Gothic", color: "#00ff00" });
const sk1 = new Skin({ fill: "#404040" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st3 = new Style({ font: "bold 28px Gothic", color: "#00ffff" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = null;
    this.s1 = false;
    this.s2 = null;
    this.sl1 = c.content("sl1");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl1) this.sl1.string = this.s1 ? "Acquiring fix..." : "Location acquired";
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 24, left: 0, width: 200, style: st0, horizontal: "center", string: "GPS Location" }),
        new Label(null, { top: 56, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "Location acquired" }),
        new RoundRect(null, { left: 10, width: 180, top: 80, height: 50, radius: 6, skin: sk1 }),
        new Label(null, { top: 84, left: 18, width: 164, style: st2, string: "Latitude" }),
        new Label(null, { top: 100, left: 18, width: 164, style: st3, string: "--°" }),
        new RoundRect(null, { left: 10, width: 180, top: 138, height: 50, radius: 6, skin: sk1 }),
        new Label(null, { top: 142, left: 18, width: 164, style: st2, string: "Longitude" }),
        new Label(null, { top: 158, left: 18, width: 164, style: st3, string: "--°" }),
        new Label(null, { top: 200, left: 0, width: 200, style: st2, horizontal: "center", string: "Press SELECT to refresh" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
