// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/health.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const sk1 = new Skin({ fill: "#404040" });
const st1 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "bold 24px Gothic", color: "#00ffff" });
const st3 = new Style({ font: "bold 24px Gothic", color: "#00ff00" });
const st4 = new Style({ font: "bold 24px Gothic", color: "#ff8000" });
const st5 = new Style({ font: "bold 24px Gothic", color: "#ff0000" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.tl0 = c.content("tl0");
  }
  onDisplaying(app) {
    this.refresh();
    this._tick = () => this.onTimeChanged();
    watch.addEventListener('minutechange', this._tick);
  }
  onTimeChanged() {
    this.refresh();
  }
  onUndisplaying(app) {
    if (this._tick) watch.removeEventListener('minutechange', this._tick);
  }
  refresh() {
    const d = new Date();
    if (this.tl0) this.tl0.string = pad(d.getHours()) + ":" + pad(d.getMinutes());
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 10, left: 0, width: 200, style: st0, horizontal: "center", name: "tl0", string: "09:07" }),
        new Content(null, { left: 10, width: 85, top: 70, height: 50, skin: sk1 }),
        new Label(null, { top: 72, left: 10, width: 85, style: st1, horizontal: "center", string: "Steps" }),
        new Label(null, { top: 88, left: 10, width: 85, style: st2, horizontal: "center", string: "5432" }),
        new Content(null, { left: 105, width: 85, top: 70, height: 50, skin: sk1 }),
        new Label(null, { top: 72, left: 105, width: 85, style: st1, horizontal: "center", string: "Distance" }),
        new Label(null, { top: 88, left: 105, width: 85, style: st3, horizontal: "center", string: "3.8km" }),
        new Content(null, { left: 10, width: 85, top: 130, height: 50, skin: sk1 }),
        new Label(null, { top: 132, left: 10, width: 85, style: st1, horizontal: "center", string: "Calories" }),
        new Label(null, { top: 148, left: 10, width: 85, style: st4, horizontal: "center", string: "210" }),
        new Content(null, { left: 105, width: 85, top: 130, height: 50, skin: sk1 }),
        new Label(null, { top: 132, left: 105, width: 85, style: st1, horizontal: "center", string: "Heart" }),
        new Label(null, { top: 148, left: 105, width: 85, style: st5, horizontal: "center", string: "72" }),
        new Label(null, { top: 195, left: 0, width: 200, style: st1, horizontal: "center", string: "Sleep: 7h 0m" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
