// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/image.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#ffffff" });
const tex0 = new Texture("batman.png");
const tsk0 = new Skin({ texture: tex0, x: 0, y: 0, width: 140, height: 70 });
const st0 = new Style({ font: "18px Gothic", color: "#000000" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
      new Content(null, { left: 30, width: 140, top: 79, height: 70, skin: tsk0 }),
      new Label(null, { top: 169, left: 0, width: 200, style: st0, horizontal: "center", string: "Na na na na na na na na" })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
