// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/layered-cards.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#000055" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const sk2 = new Skin({ fill: "#404040" });
const sk3 = new Skin({ fill: "#00ff00" });
const st1 = new Style({ font: "18px Gothic", color: "#c0c0c0" });
const sk4 = new Skin({ fill: "#0000ff" });
const sk5 = new Skin({ fill: "#ff0000" });
const sk6 = new Skin({ fill: "#ffffff" });
const st2 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st3 = new Style({ font: "14px Gothic", color: "#ffffff" });
const sk7 = new Skin({ fill: "#005500" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, height: 22, skin: sk1 }),
          new Label(null, { top: 2, left: 0, width: 200, style: st0, horizontal: "center", string: "System Stats" })
        ] }),
        new Container(null, { left: 10, right: 0, top: 28, contents: [
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 36, skin: sk2 }),
            new Container(null, { left: 8, right: 0, top: 6, contents: [
              new RoundRect(null, { left: 0, top: 0, width: 16, height: 16, radius: 8, skin: sk3 }),
              new Label(null, { top: 0, left: 48, width: 100, style: st0, string: "CPU" }),
              new Label(null, { top: 0, left: 156, width: 40, style: st1, horizontal: "right", string: "42%" })
            ] }),
            new Container(null, { left: 8, right: 0, top: 24, contents: [
              new Content(null, { left: 0, width: 164, top: 0, height: 8, skin: sk0 }),
              new Content(null, { left: 0, width: 69, top: 0, height: 8, skin: sk3 })
            ] })
          ] }),
          new Container(null, { left: 0, right: 0, top: 40, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 36, skin: sk2 }),
            new Container(null, { left: 8, right: 0, top: 6, contents: [
              new RoundRect(null, { left: 0, top: 0, width: 16, height: 16, radius: 8, skin: sk4 }),
              new Label(null, { top: 0, left: 48, width: 100, style: st0, string: "Memory" }),
              new Label(null, { top: 0, left: 156, width: 40, style: st1, horizontal: "right", string: "71%" })
            ] }),
            new Container(null, { left: 8, right: 0, top: 24, contents: [
              new Content(null, { left: 0, width: 164, top: 0, height: 8, skin: sk0 }),
              new Content(null, { left: 0, width: 116, top: 0, height: 8, skin: sk4 })
            ] })
          ] }),
          new Container(null, { left: 0, right: 0, top: 80, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 36, skin: sk2 }),
            new Container(null, { left: 8, right: 0, top: 6, contents: [
              new RoundRect(null, { left: 0, top: 0, width: 16, height: 16, radius: 8, skin: sk5 }),
              new Label(null, { top: 0, left: 48, width: 100, style: st0, string: "Disk" }),
              new Label(null, { top: 0, left: 156, width: 40, style: st1, horizontal: "right", string: "88%" })
            ] }),
            new Container(null, { left: 8, right: 0, top: 24, contents: [
              new Content(null, { left: 0, width: 164, top: 0, height: 8, skin: sk0 }),
              new Content(null, { left: 0, width: 144, top: 0, height: 8, skin: sk5 })
            ] })
          ] })
        ] }),
        new Container(null, { left: 10, right: 0, top: 146, contents: [
          new Content(null, { left: 0, width: 180, top: 0, height: 28, skin: sk6 }),
          new Label(null, { top: 2, left: 4, width: 172, style: st2, string: "Notes" }),
          new Container(null, { left: 0, right: 0, top: 32, contents: [
            new Label(null, { top: 0, left: 4, width: 172, style: st3, string: "Nested via Card children." })
          ] })
        ] }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 206, height: 22, skin: sk7 }),
          new Label(null, { top: 208, left: 0, width: 200, style: st3, horizontal: "center", string: "layered-cards demo" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
