// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/layout-demo.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const sk1 = new Skin({ fill: "#ff0000" });
const sk2 = new Skin({ fill: "#00ff00" });
const sk3 = new Skin({ fill: "#0000ff" });
const sk4 = new Skin({ fill: "#ffff00" });
const sk5 = new Skin({ fill: "#404040" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "18px Gothic", color: "#00ffff" });
const st3 = new Style({ font: "18px Gothic", color: "#ff8000" });
const sk6 = new Skin({ fill: "#ff00ff" });
const sk7 = new Skin({ fill: "#00ffff" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 4, left: 0, width: 200, style: st0, horizontal: "center", string: "Layout Demo" }),
        new Container(null, { left: 20, right: 0, top: 28, contents: [
          new RoundRect(null, { left: 0, top: 0, width: 32, height: 32, radius: 16, skin: sk1 }),
          new RoundRect(null, { left: 48, top: 0, width: 32, height: 32, radius: 16, skin: sk2 }),
          new RoundRect(null, { left: 96, top: 0, width: 32, height: 32, radius: 16, skin: sk3 }),
          new RoundRect(null, { left: 144, top: 0, width: 32, height: 32, radius: 16, skin: sk4 })
        ] }),
        new Container(null, { left: 10, right: 0, top: 68, contents: [
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 30, skin: sk5 }),
            new Label(null, { top: 6, left: 8, width: 164, style: st1, string: "First Card" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 36, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 30, skin: sk5 }),
            new Label(null, { top: 6, left: 8, width: 164, style: st2, string: "Second Card" })
          ] }),
          new Container(null, { left: 0, right: 0, top: 72, contents: [
            new Content(null, { left: 0, width: 180, top: 0, height: 30, skin: sk5 }),
            new Label(null, { top: 6, left: 8, width: 164, style: st3, string: "Third Card" })
          ] })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
