// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/memory-monitor.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "bold 42px Bitham", color: "#55ffff" });
const st2 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "18px Gothic", color: "#aaaaaa" });
const st4 = new Style({ font: "14px Gothic", color: "#ffaa00" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s1 = "none";
    this.sl5 = c.content("sl5");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl5) this.sl5.string = "" + this.s1;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "Memory" }),
        new Label(null, { top: 65, left: 0, width: 200, style: st1, horizontal: "center", string: "0%" }),
        new Label(null, { top: 130, left: 0, width: 200, style: st2, horizontal: "center", string: "used: 0" }),
        new Label(null, { top: 155, left: 0, width: 200, style: st2, horizontal: "center", string: "free: 0" }),
        new Label(null, { top: 180, left: 0, width: 200, style: st3, horizontal: "center", string: "largest: 0" }),
        new Label(null, { top: 205, left: 0, width: 200, style: st4, horizontal: "center", name: "sl5", string: "pressure: none" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
