// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/menu-layer.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#404040" });
const st0 = new Style({ font: "bold 14px Gothic", color: "#ffffff" });
const sk2 = new Skin({ fill: "#00ffff" });
const st1 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st2 = new Style({ font: "14px Gothic", color: "#000000" });
const st3 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st4 = new Style({ font: "14px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = "";
    this.s1 = 0;
    this.s2 = 0;
    this.sr2 = c.content("sr2");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "back", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "back") { this.s0 = ""; this.refresh(); }
  }
  refresh() {
    if (this.sr2) this.sr2.skin = (this.s1 !== 0) ? sk0 : sk2;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, right: 0, top: 0, height: 24, skin: sk1 }),
            new Label(null, { top: 2, left: 4, width: 192, style: st0, string: "Settings" }),
            new Content(null, { left: 0, right: 0, top: 24, height: 36, skin: sk2, name: "sr2" }),
            new Label(null, { top: 26, left: 8, width: 184, style: st1, string: "Notifications" }),
            new Label(null, { top: 44, left: 8, width: 184, style: st2, string: "Manage alerts" }),
            new Content(null, { left: 0, right: 0, top: 60, height: 36, skin: sk0 }),
            new Label(null, { top: 62, left: 8, width: 184, style: st3, string: "Display" }),
            new Label(null, { top: 80, left: 8, width: 184, style: st4, string: "Brightness & theme" }),
            new Content(null, { left: 0, right: 0, top: 96, height: 36, skin: sk0 }),
            new Label(null, { top: 98, left: 8, width: 184, style: st3, string: "Bluetooth" }),
            new Label(null, { top: 116, left: 8, width: 184, style: st4, string: "Connected" }),
            new Content(null, { left: 0, right: 0, top: 132, height: 24, skin: sk1 }),
            new Label(null, { top: 134, left: 4, width: 192, style: st0, string: "About" }),
            new Content(null, { left: 0, right: 0, top: 156, height: 36, skin: sk0 }),
            new Label(null, { top: 158, left: 8, width: 184, style: st3, string: "Version" }),
            new Label(null, { top: 176, left: 8, width: 184, style: st4, string: "v2.1.0" }),
            new Content(null, { left: 0, right: 0, top: 192, height: 36, skin: sk0 }),
            new Label(null, { top: 194, left: 8, width: 184, style: st3, string: "Model" }),
            new Label(null, { top: 212, left: 8, width: 184, style: st4, string: "Pebble Time 2" })
          ] })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
