// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/multiview.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#c0c0c0" });
const sk1 = new Skin({ fill: "#0000ff" });
const st2 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk2 = new Skin({ fill: "#404040" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.content("br_s0_v0").first;
    this.s0 = "home";
    this.br_s0_v0 = app.content("br_s0_v0");
    this.br_s0_v1 = app.content("br_s0_v1");
    this.br_s0_v2 = app.content("br_s0_v2");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 = "settings"; this.refresh(); }
    if (name === "down") { this.s0 = "about"; this.refresh(); }
    if (name === "select") { this.s0 = "home"; this.refresh(); }
  }
  refresh() {
    this.br_s0_v0.visible = (this.s0 === "home");
    this.br_s0_v1.visible = (this.s0 === "settings");
    this.br_s0_v2.visible = (this.s0 === "about");
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
    new Container(null, { name: "br_s0_v0", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Label(null, { top: 40, left: 0, width: 200, style: st0, horizontal: "center", string: "Home" }),
          new Label(null, { top: 100, left: 0, width: 200, style: st1, horizontal: "center", string: "UP=Settings DOWN=About" })
        ] })
    ] }),
    new Container(null, { name: "br_s0_v1", visible: false, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk1 }),
          new Label(null, { top: 40, left: 0, width: 200, style: st0, horizontal: "center", string: "Settings" }),
          new Label(null, { top: 100, left: 10, width: 180, style: st2, string: "Brightness: 80%" }),
          new Label(null, { top: 200, left: 0, width: 200, style: st3, horizontal: "center", string: "SELECT for home" })
        ] })
    ] }),
    new Container(null, { name: "br_s0_v2", visible: false, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk2 }),
          new Label(null, { top: 40, left: 0, width: 200, style: st0, horizontal: "center", string: "About" }),
          new Label(null, { top: 100, left: 10, width: 180, style: st2, string: "react-pebble v0.1" }),
          new Label(null, { top: 130, left: 10, width: 180, style: st3, string: "Compiled to piu" }),
          new Label(null, { top: 200, left: 0, width: 200, style: st3, horizontal: "center", string: "SELECT for home" })
        ] })
    ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
