// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/multi-click.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "bold 24px Gothic", color: "#00ffff" });
const st3 = new Style({ font: "bold 24px Gothic", color: "#00ff00" });
const st4 = new Style({ font: "bold 24px Gothic", color: "#ffff00" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.s1 = 0;
    this.s2 = "idle";
    this.s3 = false;
    this.sl2 = c.content("sl2");
    this.sl4 = c.content("sl4");
    this.sl6 = c.content("sl6");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl2) this.sl2.string = "" + this.s0;
    if (this.sl4) this.sl4.string = "" + this.s1;
    if (this.sl6) this.sl6.string = "" + this.s2;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
        new Label(null, { top: 4, left: 4, width: 192, style: st0, string: "Multi-Click" }),
        new Label(null, { top: 40, left: 0, width: 200, style: st1, horizontal: "center", string: "Double-click SELECT:" }),
        new Label(null, { top: 58, left: 0, width: 200, style: st2, horizontal: "center", name: "sl2", string: "0" }),
        new Label(null, { top: 95, left: 0, width: 200, style: st1, horizontal: "center", string: "Hold UP (repeat):" }),
        new Label(null, { top: 113, left: 0, width: 200, style: st3, horizontal: "center", name: "sl4", string: "0" }),
        new Label(null, { top: 155, left: 0, width: 200, style: st1, horizontal: "center", string: "DOWN = 2s timer:" }),
        new Label(null, { top: 173, left: 0, width: 200, style: st4, horizontal: "center", name: "sl6", string: "idle" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
