// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/number-window.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st2 = new Style({ font: "18px Gothic", color: "#404040" });
const st3 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 15;
    this.s1 = false;
    this.sl1 = c.content("sl1");
    this.sl0 = c.content("sl0");
    this.sl2 = c.content("sl2");
    this.sl3 = c.content("sl3");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "back", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "back") { this.s0 = 15; this.refresh(); }
  }
  refresh() {
    if (this.sl1) this.sl1.string = "" + this.s0;
    if (this.sl0) this.sl0.string = this.s1 ? "Timer set to" : "Set Timer (min)";
    if (this.sl2) this.sl2.string = this.s1 ? "minutes" : "UP/DOWN to adjust";
    if (this.sl3) this.sl3.string = this.s1 ? "BACK to reset" : "SELECT to confirm";
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 40, left: 0, width: 200, style: st0, horizontal: "center", name: "sl0", string: "Set Timer (min)" }),
        new Label(null, { top: 85, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "15" }),
        new Label(null, { top: 150, left: 0, width: 200, style: st2, horizontal: "center", name: "sl2", string: "UP/DOWN to adjust" }),
        new Label(null, { top: 180, left: 0, width: 200, style: st3, horizontal: "center", name: "sl3", string: "SELECT to confirm" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
