// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/round-safe.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });
const sk2 = new Skin({ fill: "#404040" });
const st2 = new Style({ font: "14px Gothic", color: "#00ffff" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Container(null, { left: 8, right: 0, top: 8, contents: [
          new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
          new Label(null, { top: 4, left: 4, width: 180, style: st0, string: "Round Safe" }),
          new Label(null, { top: 40, left: 0, width: 180, style: st1, string: "This content is" }),
          new Label(null, { top: 60, left: 0, width: 180, style: st1, string: "inset to avoid" }),
          new Label(null, { top: 80, left: 0, width: 180, style: st1, string: "round edges." }),
          new RoundRect(null, { left: 0, width: 180, top: 110, height: 36, radius: 6, skin: sk2 }),
          new Label(null, { top: 118, left: 4, width: 172, style: st2, string: "Display: 192x220 (rect)" }),
          new RoundRect(null, { left: 0, width: 180, top: 152, height: 36, radius: 6, skin: sk2 }),
          new Label(null, { top: 160, left: 4, width: 172, style: st2, string: "Offset: x=4 y=4" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
