// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/settings.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const sk1 = new Skin({ fill: "#404040" });
const st1 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st2 = new Style({ font: "bold 24px Gothic", color: "#00ffff" });
const st3 = new Style({ font: "18px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.s1 = 18;
    this.sl4 = c.content("sl4");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s1 += 2; this.refresh(); }
    if (name === "down") { this.s1 -= 2; this.refresh(); }
    if (name === "select") { this.s0 += 1; this.refresh(); }
  }
  refresh() {
    if (this.sl4) this.sl4.string = "" + this.s1;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 8, left: 0, width: 170, style: st0, horizontal: "center", string: "Settings" }),
        new RoundRect(null, { left: 10, width: 160, top: 44, height: 50, radius: 8, skin: sk1 }),
        new Label(null, { top: 48, left: 18, width: 144, style: st1, string: "Theme (SELECT to cycle)" }),
        new Label(null, { top: 66, left: 18, width: 144, style: st2, string: "dark" }),
        new RoundRect(null, { left: 10, width: 160, top: 102, height: 50, radius: 8, skin: sk1 }),
        new Label(null, { top: 106, left: 18, width: 144, style: st1, string: "Font Size (UP/DOWN)" }),
        new Label(null, { top: 124, left: 18, width: 144, style: st2, name: "sl4", string: "18px" }),
        new RoundRect(null, { left: 10, width: 160, top: 160, height: 50, radius: 8, skin: sk1 }),
        new Label(null, { top: 164, left: 18, width: 144, style: st1, string: "Preview" }),
        new Label(null, { top: 182, left: 18, width: 144, style: st3, string: "Hello Pebble!" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
