// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/simple-menu.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const sk2 = new Skin({ fill: "#00ffff" });
const st1 = new Style({ font: "14px Gothic", color: "#000000" });
const st2 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#ffffff" });
const st4 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = "None";
    this.s1 = 0;
    this.s2 = 0;
    this.sl9 = c.content("sl9");
    this.sr2 = c.content("sr2");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl9) this.sl9.string = "" + this.s0;
    if (this.sr2) this.sr2.skin = (this.s1 !== 0) ? sk0 : sk2;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
        new Label(null, { top: 4, left: 4, width: 192, style: st0, string: "Simple Menu" }),
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
            new Content(null, { left: 0, right: 0, top: 0, height: 36, skin: sk2, name: "sr2" }),
            new Label(null, { top: 2, left: 8, width: 184, style: st0, string: "Inbox" }),
            new Label(null, { top: 20, left: 8, width: 184, style: st1, string: "3 new messages" }),
            new Content(null, { left: 0, right: 0, top: 36, height: 36, skin: sk0 }),
            new Label(null, { top: 38, left: 8, width: 184, style: st2, string: "Sent" }),
            new Label(null, { top: 56, left: 8, width: 184, style: st3, string: "12 items" }),
            new Content(null, { left: 0, right: 0, top: 72, height: 36, skin: sk0 }),
            new Label(null, { top: 74, left: 8, width: 184, style: st2, string: "Drafts" }),
            new Label(null, { top: 92, left: 8, width: 184, style: st3, string: "1 draft" }),
            new Content(null, { left: 0, right: 0, top: 108, height: 36, skin: sk0 }),
            new Label(null, { top: 116, left: 8, width: 184, style: st2, string: "Trash" }),
            new Content(null, { left: 0, right: 0, top: 144, height: 36, skin: sk0 }),
            new Label(null, { top: 152, left: 8, width: 184, style: st2, string: "Settings" })
          ] })
        ] }),
        new Label(null, { top: 200, left: 0, width: 200, style: st4, horizontal: "center", name: "sl9", string: "Selected: None" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
