// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/smartstrap-demo.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "14px Gothic", color: "#aaffaa" });
const st2 = new Style({ font: "14px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#ffaa55" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = false;
    this.s1 = 0;
    this.s2 = 0;
    this.sl1 = c.content("sl1");
    this.sl2 = c.content("sl2");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl1) this.sl1.string = this.s0 ? "Available: yes" : "Available: no";
    if (this.sl2) this.sl2.string = "" + this.s1;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 12, left: 0, width: 200, style: st0, horizontal: "center", string: "Smartstrap" }),
        new Label(null, { top: 50, left: 4, width: 192, style: st1, name: "sl1", string: "Available: no" }),
        new Label(null, { top: 80, left: 4, width: 192, style: st2, name: "sl2", string: "Last byte: 0x0" }),
        new Label(null, { top: 130, left: 4, width: 192, style: st3, string: "UP: read" }),
        new Label(null, { top: 154, left: 4, width: 192, style: st3, string: "DOWN: write 0x42" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
