// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/sports.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "bold 42px Bitham", color: "#00ff00" });
const st2 = new Style({ font: "18px Gothic", color: "#55ffff" });
const st3 = new Style({ font: "14px Gothic", color: "#aaaaaa" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = 0;
    this.s1 = "stopped";
    this.sl1 = c.content("sl1");
    this.sl2 = c.content("sl2");
  }
  onDisplaying(app) {
    this.refresh();
  }
  refresh() {
    if (this.sl1) this.sl1.string = "" + this.s0;
    if (this.sl2) this.sl2.string = "" + this.s1;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Label(null, { top: 30, left: 0, width: 200, style: st0, horizontal: "center", string: "Sports" }),
          new Label(null, { top: 80, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "0s" }),
          new Label(null, { top: 150, left: 0, width: 200, style: st2, horizontal: "center", name: "sl2", string: "state: stopped" }),
          new Label(null, { top: 190, left: 0, width: 200, style: st3, horizontal: "center", string: "SELECT toggles play/pause" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
