// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/stopwatch.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#404040" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "bold 24px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk2 = new Skin({ fill: "#00ff00" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = false;
    this.s1 = "00:00";
    this._startTime_s0 = Date.now();
    this.sl0 = c.content("sl0");
    this.sl1 = c.content("sl1");
    this.sr0 = c.content("sr0");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onTimeChanged() {
    this.refresh();
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "select") { this.s0 = !this.s0; if (this.s0) this._startTime_s0 = Date.now(); this.refresh(); }
    if (name === "down") { this.s1 = "00:00"; this.refresh(); }
  }
  refresh() {
    const d = new Date();
    if (this.sl0) this.sl0.string = this.s0 ? (function(e) { return pad(Math.floor(e / 60)) + ":" + pad(e % 60); })(Math.floor((Date.now() - this._startTime_s0) / 1000)) : "00:00";
    if (this.sl1) this.sl1.string = this.s0 ? "RUNNING" : "STOPPED";
    if (this.sr0) this.sr0.skin = this.s0 ? sk2 : sk0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0, name: "sr0" }),
        new RoundRect(null, { left: 40, top: 24, width: 120, height: 120, radius: 60, skin: sk1 }),
        new RoundRect(null, { left: 44, top: 28, width: 112, height: 112, radius: 56, skin: sk0 }),
        new Label(null, { top: 55, left: 0, width: 200, style: st0, horizontal: "center", name: "sl0", string: "00:00" }),
        new Label(null, { top: 160, left: 0, width: 200, style: st1, horizontal: "center", name: "sl1", string: "STOPPED" }),
        new Label(null, { top: 200, left: 0, width: 200, style: st2, horizontal: "center", string: "SELECT start/stop · DOWN reset" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
