// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/tasks.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const sk1 = new Skin({ fill: "#ffffff" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#000000" });
const st1 = new Style({ font: "14px Gothic", color: "#404040" });
const sk2 = new Skin({ fill: "#404040" });
const st2 = new Style({ font: "bold 14px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const sk3 = new Skin({ fill: "#0000ff" });
const st4 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st5 = new Style({ font: "18px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.content("br_s0_v0").first;
    this.s0 = "list";
    this.s1 = 0;
    this.sl1 = c.content("sl1");
    this.sr2 = c.content("sr2");
    this.br_s0_v0 = app.content("br_s0_v0");
    this.br_s0_v1 = app.content("br_s0_v1");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "back", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s1 -= 1; this.refresh(); }
    if (name === "down") { this.s1 += 1; this.refresh(); }
    if (name === "select") { this.s0 = "detail"; this.refresh(); }
    if (name === "back") { this.s0 = "list"; this.refresh(); }
  }
  refresh() {
    this.sl1.string = "" + this.s1;
    this.sr2.skin = (this.s1 !== 0) ? sk0 : sk2;
    this.br_s0_v0.visible = (this.s0 === "list");
    this.br_s0_v1.visible = (this.s0 === "detail");
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
    new Container(null, { name: "br_s0_v0", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
          new Content(null, { left: 0, right: 0, top: 0, height: 28, skin: sk1 }),
          new Label(null, { top: 4, left: 4, width: 140, style: st0, string: "My Tasks" }),
          new Label(null, { top: 4, left: 148, width: 48, style: st1, horizontal: "right", name: "sl1", string: "1/3" }),
          new Content(null, { left: 0, right: 0, top: 30, height: 60, skin: sk2, name: "sr2" }),
          new Label(null, { top: 34, left: 8, width: 184, style: st2, string: "Fix login bug" }),
          new Label(null, { top: 52, left: 8, width: 184, style: st3, string: "In Progress" }),
          new Content(null, { left: 0, right: 0, top: 92, height: 60, skin: sk0 }),
          new Label(null, { top: 96, left: 8, width: 184, style: st2, string: "Update docs" }),
          new Label(null, { top: 114, left: 8, width: 184, style: st3, string: "To Do" }),
          new Content(null, { left: 0, right: 0, top: 154, height: 60, skin: sk0 }),
          new Label(null, { top: 158, left: 8, width: 184, style: st2, string: "Deploy v2" }),
          new Label(null, { top: 176, left: 8, width: 184, style: st3, string: "Done" }),
          new Label(null, { top: 216, left: 0, width: 200, style: st1, horizontal: "center", string: "UP/DOWN nav, SELECT detail" })
        ] })
    ] }),
    new Container(null, { name: "br_s0_v1", visible: false, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
          new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk3 }),
          new Label(null, { top: 16, left: 0, width: 200, style: st4, horizontal: "center", string: "Task Detail" }),
          new Label(null, { top: 60, left: 10, width: 180, style: st5, string: "Task #0" }),
          new Label(null, { top: 90, left: 10, width: 180, style: st3, string: "Status: In Progress" }),
          new Label(null, { top: 120, left: 10, width: 180, style: st3, string: "Priority: High" }),
          new Label(null, { top: 200, left: 0, width: 200, style: st3, horizontal: "center", string: "BACK to return" })
        ] })
    ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
