// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/time-utils.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#aaaaaa" });
const st2 = new Style({ font: "14px Gothic", color: "#55ffff" });
const st3 = new Style({ font: "14px Gothic", color: "#ffaa00" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "09:07 AM" }),
        new Label(null, { top: 85, left: 0, width: 200, style: st1, horizontal: "center", string: "24h style: no" }),
        new Label(null, { top: 115, left: 0, width: 200, style: st2, horizontal: "center", string: "HH:mm → 09:07" }),
        new Label(null, { top: 140, left: 0, width: 200, style: st2, horizontal: "center", string: "hh:mm a → 09:07 AM" }),
        new Label(null, { top: 175, left: 0, width: 200, style: st3, horizontal: "center", string: "elapsed today: 0s" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
