// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/timeline-subs.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "14px Gothic", color: "#aaffaa" });
const st2 = new Style({ font: "14px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#ffaa55" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = null;
    this.s1 = null;
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "up", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
    new PebbleButton({ type: "down", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "up") { this.s0 = "news"; this.refresh(); }
    if (name === "down") { this.s0 = "news"; this.refresh(); }
  }
  refresh() {
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 8, left: 4, width: 192, style: st0, horizontal: "center", string: "Subscriptions" }),
        new Label(null, { top: 40, left: 4, width: 192, style: st1, string: "Topics:" }),
        new Label(null, { top: 60, left: 4, width: 192, style: st2, string: "(loading)" }),
        new Label(null, { top: 110, left: 4, width: 192, style: st3, string: "UP: subscribe \"news\"" }),
        new Label(null, { top: 134, left: 4, width: 192, style: st3, string: "DOWN: unsubscribe \"news\"" }),
        new Label(null, { top: 158, left: 4, width: 192, style: st3, string: "SELECT: refresh list" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
