// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/tokens.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "14px Gothic", color: "#aaffaa" });
const st2 = new Style({ font: "14px Gothic", color: "#ffffff" });

const bgSkin = new Skin({ fill: "#000000" });

const WatchApp = Application.template(() => ({
  skin: bgSkin,

  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 8, left: 4, width: 192, style: st0, horizontal: "center", string: "Identity Tokens" }),
        new Label(null, { top: 40, left: 4, width: 192, style: st1, string: "Account:" }),
        new Label(null, { top: 58, left: 4, width: 192, style: st2, string: "(loading)" }),
        new Label(null, { top: 86, left: 4, width: 192, style: st1, string: "Watch:" }),
        new Label(null, { top: 104, left: 4, width: 192, style: st2, string: "(loading)" }),
        new Label(null, { top: 132, left: 4, width: 192, style: st1, string: "Timeline:" }),
        new Label(null, { top: 150, left: 4, width: 192, style: st2, string: "(loading)" })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
