// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/views.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";
import PebbleButton from "pebble/button";


const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 18px Gothic", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#ffffff" });
const st2 = new Style({ font: "14px Gothic", color: "#c0c0c0" });

const bgSkin = new Skin({ fill: "#000000" });

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = false;
    this.cv_s0_1 = c.content("cv_s0_1");
    this.cv_s0_2 = c.content("cv_s0_2");
    this.cv_s0_3 = c.content("cv_s0_3");
  }
  onDisplaying(app) {
    this.refresh();
    new PebbleButton({ type: "select", onPush: (pushed, name) => { if (pushed) this.onButton({ button: name }); } });
  }
  onButton(e) {
    const name = e && e.button;
    if (name === "select") { this.s0 = !this.s0; this.refresh(); }
  }
  refresh() {
    this.cv_s0_1.visible = !!this.s0;
    this.cv_s0_2.visible = !!this.s0;
    this.cv_s0_3.visible = !!this.s0;
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Container(null, { name: "cv_s0_1", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Label(null, { top: 20, left: 0, width: 200, style: st0, horizontal: "center", string: "List View" })
        ] }),
        new Container(null, { name: "cv_s0_2", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Label(null, { top: 60, left: 10, width: 180, style: st1, string: "Item 1" })
        ] }),
        new Container(null, { name: "cv_s0_3", visible: true, left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Label(null, { top: 200, left: 0, width: 200, style: st2, horizontal: "center", string: "SELECT for detail" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
