// Auto-generated by react-pebble compile-to-piu (v3 with state reactivity)
// Source: examples/weather.tsx rendered in Node mock mode.
//
// Regenerate: npx tsx scripts/compile-to-piu.ts > pebble-spike/src/embeddedjs/main.js

import {} from "piu/MC";



const sk0 = new Skin({ fill: "#000000" });
const st0 = new Style({ font: "bold 42px Bitham", color: "#ffffff" });
const st1 = new Style({ font: "18px Gothic", color: "#c0c0c0" });
const sk1 = new Skin({ fill: "#404040" });
const sk2 = new Skin({ fill: "#ffff00" });
const st2 = new Style({ font: "bold 28px Gothic", color: "#ffffff" });
const st3 = new Style({ font: "14px Gothic", color: "#c0c0c0" });
const st4 = new Style({ font: "bold 14px Gothic", color: "#ffffff" });
const sk3 = new Skin({ fill: "#c0c0c0" });
const sk4 = new Skin({ fill: "#00ffff" });

const bgSkin = new Skin({ fill: "#000000" });

function pad(n) { return n < 10 ? "0" + n : "" + n; }
const days = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const months = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

class AppBehavior extends Behavior {
  onCreate(app) {
    const c = app.first;
    this.s0 = "2026-01-14T22:07:03.000Z";
    this.tl0 = c.content("tl0");
    this.tl1 = c.content("tl1");
  }
  onDisplaying(app) {
    this.refresh();
    app.interval = 1000;
    app.start();
  }
  onTimeChanged() {
    this.refresh();
  }
  refresh() {
    const d = new Date();
    this.tl0.string = pad(d.getHours()) + ":" + pad(d.getMinutes());
    this.tl1.string = days[d.getDay()] + " " + months[d.getMonth()] + " " + d.getDate();
  }
}

const WatchApp = Application.template(() => ({
  skin: bgSkin,
  Behavior: AppBehavior,
  contents: [
      new Container(null, { left: 0, right: 0, top: 0, bottom: 0, contents: [
        new Content(null, { left: 0, right: 0, top: 0, bottom: 0, skin: sk0 }),
        new Label(null, { top: 8, left: 0, width: 200, style: st0, horizontal: "center", name: "tl0", string: "09:07" }),
        new Label(null, { top: 55, left: 0, width: 200, style: st1, horizontal: "center", name: "tl1", string: "Thu Jan 15" }),
        new Content(null, { left: 20, width: 160, top: 80, height: 1, skin: sk1 }),
        new RoundRect(null, { left: 20, top: 90, width: 40, height: 40, radius: 20, skin: sk2 }),
        new Label(null, { top: 90, left: 70, width: 120, style: st2, string: "72°F" }),
        new Label(null, { top: 118, left: 70, width: 120, style: st3, string: "Sunny" }),
        new Content(null, { left: 20, width: 160, top: 142, height: 1, skin: sk1 }),
        new Container(null, { left: 0, right: 0, top: 150, contents: [
          new RoundRect(null, { left: 10, top: 6, width: 16, height: 16, radius: 8, skin: sk2 }),
          new Label(null, { top: 2, left: 32, width: 40, style: st4, string: "Thu" }),
          new Label(null, { top: 2, left: 80, width: 50, style: st3, string: "75°/58°" })
        ] }),
        new Container(null, { left: 0, right: 0, top: 174, contents: [
          new RoundRect(null, { left: 10, top: 6, width: 16, height: 16, radius: 8, skin: sk3 }),
          new Label(null, { top: 2, left: 32, width: 40, style: st4, string: "Fri" }),
          new Label(null, { top: 2, left: 80, width: 50, style: st3, string: "68°/52°" })
        ] }),
        new Container(null, { left: 0, right: 0, top: 198, contents: [
          new RoundRect(null, { left: 10, top: 6, width: 16, height: 16, radius: 8, skin: sk4 }),
          new Label(null, { top: 2, left: 32, width: 40, style: st4, string: "Sat" }),
          new Label(null, { top: 2, left: 80, width: 50, style: st3, string: "62°/48°" })
        ] })
      ] })
  ],
}));

export default new WatchApp(null, { touchCount: 0, pixels: screen.width * 4 });
